/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Count of actions by type.
 *
 * @param action Action type (SPEAK, DEFER, REJECT, etc.)
 * @param count Number of times action was taken
 * @param percentage Percentage of total actions
 */
@Serializable

data class ActionCount (

    /* Action type (SPEAK, DEFER, REJECT, etc.) */
    @SerialName(value = "action") @Required val action: kotlin.String,

    /* Number of times action was taken */
    @SerialName(value = "count") @Required val count: kotlin.Int,

    /* Percentage of total actions */
    @SerialName(value = "percentage") @Required val percentage: kotlin.Double

) {


}
