/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ActionParameters
import ai.ciris.api.models.HandlerActionType
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Result from Action Selection DMA - the meta-decision maker.
 *
 * @param selectedAction The chosen handler action
 * @param actionParameters
 * @param rationale Reasoning for this action selection (REQUIRED)
 * @param rawLlmResponse
 * @param reasoning
 * @param evaluationTimeMs
 * @param resourceUsage
 * @param userPrompt
 */
@Serializable

data class ActionSelectionDMAResult (

    /* The chosen handler action */
    @SerialName(value = "selected_action") @Required val selectedAction: HandlerActionType,

    @SerialName(value = "action_parameters") @Required val actionParameters: ActionParameters,

    /* Reasoning for this action selection (REQUIRED) */
    @SerialName(value = "rationale") @Required val rationale: kotlin.String,

    @SerialName(value = "raw_llm_response") val rawLlmResponse: kotlin.String? = null,

    @SerialName(value = "reasoning") val reasoning: kotlin.String? = null,

    @SerialName(value = "evaluation_time_ms") val evaluationTimeMs: kotlin.Double? = null,

    @SerialName(value = "resource_usage") val resourceUsage: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null,

    @SerialName(value = "user_prompt") val userPrompt: kotlin.String? = null

) {


}
