/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Metrics for an adapter.
 *
 * @param messagesProcessed Total messages processed
 * @param errorsCount Total errors
 * @param uptimeSeconds Adapter uptime in seconds
 * @param lastError
 * @param lastErrorTime
 */
@Serializable

data class AdapterMetrics (

    /* Total messages processed */
    @SerialName(value = "messages_processed") val messagesProcessed: kotlin.Int? = 0,

    /* Total errors */
    @SerialName(value = "errors_count") val errorsCount: kotlin.Int? = 0,

    /* Adapter uptime in seconds */
    @SerialName(value = "uptime_seconds") val uptimeSeconds: kotlin.Double? = (0.0).toDouble(),

    @SerialName(value = "last_error") val lastError: kotlin.String? = null,

    @SerialName(value = "last_error_time") val lastErrorTime: kotlinx.datetime.Instant? = null

) {


}
