/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.AdapterOperationResultDetailsValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Result of an adapter operation.
 *
 * @param success Whether operation succeeded
 * @param adapterId Adapter ID
 * @param adapterType
 * @param message
 * @param error
 * @param details
 */
@Serializable

data class AdapterOperationResult (

    /* Whether operation succeeded */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    /* Adapter ID */
    @SerialName(value = "adapter_id") @Required val adapterId: kotlin.String,

    @SerialName(value = "adapter_type") val adapterType: kotlin.String? = null,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "error") val error: kotlin.String? = null,

    @SerialName(value = "details") val details: kotlin.collections.Map<kotlin.String, AdapterOperationResultDetailsValue>? = null

) {


}
