/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.AgentLineage
import ai.ciris.api.models.ServiceAvailability

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Agent identity and capabilities.
 *
 * @param agentId Unique agent identifier
 * @param name Agent name
 * @param purpose Agent's purpose
 * @param createdAt When agent was created
 * @param lineage Agent lineage information
 * @param varianceThreshold Identity variance threshold
 * @param tools Available tools
 * @param handlers Active handlers
 * @param services Service availability
 * @param permissions Agent permissions
 */
@Serializable

data class AgentIdentity (

    /* Unique agent identifier */
    @SerialName(value = "agent_id") @Required val agentId: kotlin.String,

    /* Agent name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Agent's purpose */
    @SerialName(value = "purpose") @Required val purpose: kotlin.String,

    /* When agent was created */
    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    /* Agent lineage information */
    @SerialName(value = "lineage") @Required val lineage: AgentLineage,

    /* Identity variance threshold */
    @SerialName(value = "variance_threshold") @Required val varianceThreshold: kotlin.Double,

    /* Available tools */
    @SerialName(value = "tools") @Required val tools: kotlin.collections.List<kotlin.String>,

    /* Active handlers */
    @SerialName(value = "handlers") @Required val handlers: kotlin.collections.List<kotlin.String>,

    /* Service availability */
    @SerialName(value = "services") @Required val services: ServiceAvailability,

    /* Agent permissions */
    @SerialName(value = "permissions") @Required val permissions: kotlin.collections.List<kotlin.String>

) {


}
