/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.CirisEngineSchemasApiAuthAPIKeyInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List of API keys.
 *
 * @param apiKeys List of API keys
 * @param total Total number of keys
 */
@Serializable

data class APIKeyListResponse (

    /* List of API keys */
    @SerialName(value = "api_keys") @Required val apiKeys: kotlin.collections.List<CirisEngineSchemasApiAuthAPIKeyInfo>,

    /* Total number of keys */
    @SerialName(value = "total") @Required val total: kotlin.Int

) {


}
