/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.AuditEntryResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List of audit entries.
 *
 * @param propertyEntries Audit entries
 * @param total Total matching entries
 * @param offset Results offset
 * @param limit Results limit
 */
@Serializable

data class AuditEntriesResponse (

    /* Audit entries */
    @SerialName(value = "entries") @Required val propertyEntries: kotlin.collections.List<AuditEntryResponse>,

    /* Total matching entries */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* Results offset */
    @SerialName(value = "offset") val offset: kotlin.Int? = 0,

    /* Results limit */
    @SerialName(value = "limit") val limit: kotlin.Int? = 100

) {


}
