/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Audit export response.
 *
 * @param format Export format
 * @param totalEntries Total entries exported
 * @param exportUrl
 * @param exportData
 */
@Serializable

data class AuditExportResponse (

    /* Export format */
    @SerialName(value = "format") @Required val format: kotlin.String,

    /* Total entries exported */
    @SerialName(value = "total_entries") @Required val totalEntries: kotlin.Int,

    @SerialName(value = "export_url") val exportUrl: kotlin.String? = null,

    @SerialName(value = "export_data") val exportData: kotlin.String? = null

) {


}
