/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Metadata for a consent category.
 *
 * @param name Display name
 * @param description Category description
 */
@Serializable

data class CategoryMetadata (

    /* Display name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Category description */
    @SerialName(value = "description") @Required val description: kotlin.String

) {


}
