/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ChannelInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List of active channels.
 *
 * @param channels List of channels
 * @param totalCount Total number of channels
 */
@Serializable

data class ChannelList (

    /* List of channels */
    @SerialName(value = "channels") @Required val channels: kotlin.collections.List<ChannelInfo>,

    /* Total number of channels */
    @SerialName(value = "total_count") @Required val totalCount: kotlin.Int

) {


}
