/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from circuit breaker reset.
 *
 * @param resetCount Number of circuit breakers reset
 * @param message Status message
 * @param serviceType
 * @param servicesAffected List of affected services
 */
@Serializable

data class CircuitBreakerResetResponse (

    /* Number of circuit breakers reset */
    @SerialName(value = "reset_count") @Required val resetCount: kotlin.Int,

    /* Status message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "service_type") val serviceType: kotlin.String? = null,

    /* List of affected services */
    @SerialName(value = "services_affected") val servicesAffected: kotlin.collections.List<kotlin.String>? = null

) {


}
