/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.AdapterOperationResultDetailsValue
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Typed configuration value wrapper.
 *
 * @param stringValue
 * @param intValue
 * @param floatValue
 * @param boolValue
 * @param listValue
 * @param dictValue
 */
@Serializable

data class ConfigValue (

    @SerialName(value = "string_value") val stringValue: kotlin.String? = null,

    @SerialName(value = "int_value") val intValue: kotlin.Int? = null,

    @SerialName(value = "float_value") val floatValue: kotlin.Double? = null,

    @SerialName(value = "bool_value") val boolValue: kotlin.Boolean? = null,

    @SerialName(value = "list_value") val listValue: kotlin.collections.List<AdapterOperationResultDetailsValue>? = null,

    @SerialName(value = "dict_value") val dictValue: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null

) {


}
