/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Specific attributes for configuration nodes.  Used by the config service for storing system and behavioral configuration.
 *
 * @param createdBy Service or user that created this node
 * @param key Configuration key (unique within scope)
 * @param `value` Configuration value
 * @param description What this configuration controls
 * @param category Category: system, behavioral, ethical, operational
 * @param valueType Expected type: string, integer, float, boolean, list, dict
 * @param createdAt When this node was created
 * @param updatedAt When this node was last updated
 * @param updatedBy
 * @param tags Tags for categorization and search
 * @param version Schema version for migration support
 * @param secretRefs Secret reference UUIDs for encrypted data
 * @param validationRules Validation rules for this config
 * @param isSensitive Whether this contains sensitive data
 * @param requiresAuthority Whether changes require WiseAuthority approval
 * @param previousValue Previous value before last update
 * @param changeReason
 * @param approvedBy
 * @param scope Scope: system, channel, user
 * @param appliesTo Specific entities this applies to
 * @param isActive Whether this config is currently active
 * @param expiresAt
 */
@Serializable

data class ConfigNodeAttributes (

    /* Service or user that created this node */
    @SerialName(value = "created_by") @Required val createdBy: kotlin.String,

    /* Configuration key (unique within scope) */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* Configuration value */
    @SerialName(value = "value") @Required val `value`: kotlinx.serialization.json.JsonElement?,

    /* What this configuration controls */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Category: system, behavioral, ethical, operational */
    @SerialName(value = "category") @Required val category: kotlin.String,

    /* Expected type: string, integer, float, boolean, list, dict */
    @SerialName(value = "value_type") @Required val valueType: kotlin.String,

    /* When this node was created */
    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant? = null,

    /* When this node was last updated */
    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_by") val updatedBy: kotlin.String? = null,

    /* Tags for categorization and search */
    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null,

    /* Schema version for migration support */
    @SerialName(value = "version") val version: kotlin.Int? = 1,

    /* Secret reference UUIDs for encrypted data */
    @SerialName(value = "secret_refs") val secretRefs: kotlin.collections.List<kotlin.String>? = null,

    /* Validation rules for this config */
    @SerialName(value = "validation_rules") val validationRules: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>>? = null,

    /* Whether this contains sensitive data */
    @SerialName(value = "is_sensitive") val isSensitive: kotlin.Boolean? = false,

    /* Whether changes require WiseAuthority approval */
    @SerialName(value = "requires_authority") val requiresAuthority: kotlin.Boolean? = false,

    /* Previous value before last update */
    @SerialName(value = "previous_value") val previousValue: kotlinx.serialization.json.JsonElement? = null,

    @SerialName(value = "change_reason") val changeReason: kotlin.String? = null,

    @SerialName(value = "approved_by") val approvedBy: kotlin.String? = null,

    /* Scope: system, channel, user */
    @SerialName(value = "scope") val scope: kotlin.String? = "system",

    /* Specific entities this applies to */
    @SerialName(value = "applies_to") val appliesTo: kotlin.collections.List<kotlin.String>? = null,

    /* Whether this config is currently active */
    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null

) {


}
