/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from completing a configuration session.
 *
 * @param success Whether configuration was applied successfully
 * @param adapterType Adapter that was configured
 * @param message Human-readable result message
 * @param appliedConfig Configuration that was applied
 * @param persisted Whether configuration was persisted for startup
 */
@Serializable

data class ConfigurationCompleteResponse (

    /* Whether configuration was applied successfully */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    /* Adapter that was configured */
    @SerialName(value = "adapter_type") @Required val adapterType: kotlin.String,

    /* Human-readable result message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    /* Configuration that was applied */
    @SerialName(value = "applied_config") val appliedConfig: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

    /* Whether configuration was persisted for startup */
    @SerialName(value = "persisted") val persisted: kotlin.Boolean? = false

) {


}
