/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for consent cleanup operation.
 *
 * @param cleaned Number of records cleaned
 * @param message Cleanup result message
 */
@Serializable

data class ConsentCleanupResponse (

    /* Number of records cleaned */
    @SerialName(value = "cleaned") @Required val cleaned: kotlin.Int,

    /* Cleanup result message */
    @SerialName(value = "message") @Required val message: kotlin.String

) {


}
