/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ConsentCategory
import ai.ciris.api.models.ConsentStream

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * User's consent configuration - NO DEFAULTS, FAIL FAST.
 *
 * @param userId User identifier
 * @param stream Current consent stream
 * @param categories What they consented to
 * @param grantedAt When consent was granted
 * @param lastModified Last modification time
 * @param expiresAt
 * @param impactScore Contribution to collective learning
 * @param attributionCount Number of patterns attributed
 */
@Serializable

data class ConsentStatus (

    /* User identifier */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* Current consent stream */
    @SerialName(value = "stream") @Required val stream: ConsentStream,

    /* What they consented to */
    @SerialName(value = "categories") @Required val categories: kotlin.collections.List<@Contextual ConsentCategory>,

    /* When consent was granted */
    @SerialName(value = "granted_at") @Required val grantedAt: kotlinx.datetime.Instant,

    /* Last modification time */
    @SerialName(value = "last_modified") @Required val lastModified: kotlinx.datetime.Instant,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    /* Contribution to collective learning */
    @SerialName(value = "impact_score") val impactScore: kotlin.Double? = (0.0).toDouble(),

    /* Number of patterns attributed */
    @SerialName(value = "attribution_count") val attributionCount: kotlin.Int? = 0

) {


}
