/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ConsentRecordResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for consent query endpoint.
 *
 * @param consents List of consent records
 * @param total Total number of records
 */
@Serializable

data class ConsentQueryResponse (

    /* List of consent records */
    @SerialName(value = "consents") @Required val consents: kotlin.collections.List<ConsentRecordResponse>,

    /* Total number of records */
    @SerialName(value = "total") @Required val total: kotlin.Int

) {


}
