/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ConscienceResultDetailsValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Result from any conscience check.
 *
 * @param conscienceName Name of the conscience
 * @param passed Whether the conscience check passed
 * @param severity Severity level of the result
 * @param message Result message
 * @param overrideAction
 * @param details
 */
@Serializable

data class ConscienceResult (

    /* Name of the conscience */
    @SerialName(value = "conscience_name") @Required val conscienceName: kotlin.String,

    /* Whether the conscience check passed */
    @SerialName(value = "passed") @Required val passed: kotlin.Boolean,

    /* Severity level of the result */
    @SerialName(value = "severity") @Required val severity: ConscienceResult.Severity,

    /* Result message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "override_action") val overrideAction: kotlin.String? = null,

    @SerialName(value = "details") val details: kotlin.collections.Map<kotlin.String, ConscienceResultDetailsValue>? = null

) {

    /**
     * Severity level of the result
     *
     * Values: INFO,WARNING,ERROR,CRITICAL
     */
    @Serializable
    enum class Severity(val value: kotlin.String) {
        @SerialName(value = "info") INFO("info"),
        @SerialName(value = "warning") WARNING("warning"),
        @SerialName(value = "error") ERROR("error"),
        @SerialName(value = "critical") CRITICAL("critical");
    }

}
