/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*

/**
 * How we handle user data based on consent.  TEMPORARY: Default - we forget in 14 days PARTNERED: Explicit consent for mutual growth ANONYMOUS: Statistics only, no identity
 *
 * Values: TEMPORARY,PARTNERED,ANONYMOUS
 */
@Serializable
enum class ConsentStream(val value: kotlin.String) {

    @SerialName(value = "temporary")
    TEMPORARY("temporary"),

    @SerialName(value = "partnered")
    PARTNERED("partnered"),

    @SerialName(value = "anonymous")
    ANONYMOUS("anonymous");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ConsentStream) "$data" else null

        /**
         * Returns a valid [ConsentStream] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ConsentStream? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
