/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ConsentCategory

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Show users their contribution - REAL DATA ONLY.  User-facing name: Commons Credits Report  Commons Credits track non-monetary contributions that strengthen the community: - Sharing knowledge (patterns_contributed) - Supporting others (users_helped) - Maintaining infrastructure (interactions)  Not currency. Not scorekeeping. Recognition for contributions traditional systems ignore.
 *
 * @param userId User requesting report
 * @param totalInteractions Total interactions
 * @param patternsContributed Patterns learned
 * @param usersHelped Others benefited
 * @param categoriesActive Active categories
 * @param impactScore Overall impact
 * @param exampleContributions Example learnings (anonymized)
 */
@Serializable

data class ConsentImpactReport (

    /* User requesting report */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* Total interactions */
    @SerialName(value = "total_interactions") @Required val totalInteractions: kotlin.Int,

    /* Patterns learned */
    @SerialName(value = "patterns_contributed") @Required val patternsContributed: kotlin.Int,

    /* Others benefited */
    @SerialName(value = "users_helped") @Required val usersHelped: kotlin.Int,

    /* Active categories */
    @SerialName(value = "categories_active") @Required val categoriesActive: kotlin.collections.List<@Contextual ConsentCategory>,

    /* Overall impact */
    @SerialName(value = "impact_score") @Required val impactScore: kotlin.Double,

    /* Example learnings (anonymized) */
    @SerialName(value = "example_contributions") @Required val exampleContributions: kotlin.collections.List<kotlin.String>

) {


}
