/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ConsentCategory
import ai.ciris.api.models.ConsentStream

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Audit trail for consent changes - IMMUTABLE RECORD.
 *
 * @param entryId Unique audit entry ID
 * @param userId User whose consent changed
 * @param timestamp When change occurred
 * @param previousStream Stream before change
 * @param newStream Stream after change
 * @param previousCategories Categories before
 * @param newCategories Categories after
 * @param initiatedBy Who initiated change (user/system/dsar)
 * @param reason
 */
@Serializable

data class ConsentAuditEntry (

    /* Unique audit entry ID */
    @SerialName(value = "entry_id") @Required val entryId: kotlin.String,

    /* User whose consent changed */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* When change occurred */
    @SerialName(value = "timestamp") @Required val timestamp: kotlinx.datetime.Instant,

    /* Stream before change */
    @SerialName(value = "previous_stream") @Required val previousStream: ConsentStream,

    /* Stream after change */
    @SerialName(value = "new_stream") @Required val newStream: ConsentStream,

    /* Categories before */
    @SerialName(value = "previous_categories") @Required val previousCategories: kotlin.collections.List<@Contextual ConsentCategory>,

    /* Categories after */
    @SerialName(value = "new_categories") @Required val newCategories: kotlin.collections.List<@Contextual ConsentCategory>,

    /* Who initiated change (user/system/dsar) */
    @SerialName(value = "initiated_by") @Required val initiatedBy: kotlin.String,

    @SerialName(value = "reason") val reason: kotlin.String? = null

) {


}
