/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Track decay protocol progress - NO FAKE DELETION.
 *
 * @param userId User being forgotten
 * @param decayStarted When decay began
 * @param identitySevered Identity disconnected from patterns
 * @param patternsAnonymized Patterns converted to anonymous
 * @param decayCompleteAt When decay will complete (90 days)
 * @param safetyPatternsRetained Patterns kept for safety
 */
@Serializable

data class ConsentDecayStatus (

    /* User being forgotten */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* When decay began */
    @SerialName(value = "decay_started") @Required val decayStarted: kotlinx.datetime.Instant,

    /* Identity disconnected from patterns */
    @SerialName(value = "identity_severed") @Required val identitySevered: kotlin.Boolean,

    /* Patterns converted to anonymous */
    @SerialName(value = "patterns_anonymized") @Required val patternsAnonymized: kotlin.Boolean,

    /* When decay will complete (90 days) */
    @SerialName(value = "decay_complete_at") @Required val decayCompleteAt: kotlinx.datetime.Instant,

    /* Patterns kept for safety */
    @SerialName(value = "safety_patterns_retained") val safetyPatternsRetained: kotlin.Int? = 0

) {


}
