/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ConversationMessage

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Conversation history.
 *
 * @param messages Message history
 * @param totalCount Total messages
 * @param hasMore Whether more messages exist
 */
@Serializable

data class ConversationHistory (

    /* Message history */
    @SerialName(value = "messages") @Required val messages: kotlin.collections.List<ConversationMessage>,

    /* Total messages */
    @SerialName(value = "total_count") @Required val totalCount: kotlin.Int,

    /* Whether more messages exist */
    @SerialName(value = "has_more") @Required val hasMore: kotlin.Boolean

) {


}
