/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 * MANUALLY MODIFIED: This file handles anyOf union types that the generator
 * doesn't properly support. The OpenAPI spec defines default as:
 * anyOf: [string, integer, number, boolean, array, null]
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * Default value - can be any JSON primitive or array.
 * Wraps JsonElement to handle anyOf union types from OpenAPI spec.
 */
@Serializable(with = DefaultSerializer::class)
data class Default(
    val value: JsonElement
) {
    /**
     * Get the value as a string, or null if not a string primitive.
     */
    fun asStringOrNull(): String? = (value as? JsonPrimitive)?.contentOrNull

    /**
     * Get the value as an int, or null if not an integer primitive.
     */
    fun asIntOrNull(): Int? = (value as? JsonPrimitive)?.intOrNull

    /**
     * Get the value as a boolean, or null if not a boolean primitive.
     */
    fun asBooleanOrNull(): Boolean? = (value as? JsonPrimitive)?.booleanOrNull

    /**
     * Get the value as a list of strings, or null if not an array.
     */
    fun asStringListOrNull(): List<String>? = (value as? JsonArray)?.mapNotNull {
        (it as? JsonPrimitive)?.contentOrNull
    }

    override fun toString(): String = value.toString()
}

/**
 * Custom serializer for Default that handles any JSON value type.
 */
object DefaultSerializer : KSerializer<Default> {
    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Default) {
        encoder.encodeSerializableValue(JsonElement.serializer(), value.value)
    }

    override fun deserialize(decoder: Decoder): Default {
        val element = decoder.decodeSerializableValue(JsonElement.serializer())
        return Default(element)
    }
}
