/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.PendingDeferral

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response containing list of pending deferrals.
 *
 * @param deferrals List of pending deferrals
 * @param total Total number of pending deferrals
 */
@Serializable

data class DeferralListResponse (

    /* List of pending deferrals */
    @SerialName(value = "deferrals") @Required val deferrals: kotlin.collections.List<PendingDeferral>,

    /* Total number of pending deferrals */
    @SerialName(value = "total") @Required val total: kotlin.Int

) {


}
