/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A decision made by a DMA.
 *
 * @param dmaType Type of DMA: PDMA, CSDMA, DSDMA, ActionSelection
 * @param decision The decision: approve, reject, defer, etc.
 * @param reasoning Explanation of the decision
 * @param timestamp Decision timestamp
 * @param factorsConsidered Factors in decision
 * @param alternativesEvaluated Alternatives considered
 */
@Serializable

data class DMADecision (

    /* Type of DMA: PDMA, CSDMA, DSDMA, ActionSelection */
    @SerialName(value = "dma_type") @Required val dmaType: kotlin.String,

    /* The decision: approve, reject, defer, etc. */
    @SerialName(value = "decision") @Required val decision: kotlin.String,

    /* Explanation of the decision */
    @SerialName(value = "reasoning") @Required val reasoning: kotlin.String,

    /* Decision timestamp */
    @SerialName(value = "timestamp") @Required val timestamp: kotlinx.datetime.Instant,

    /* Factors in decision */
    @SerialName(value = "factors_considered") val factorsConsidered: kotlin.collections.List<kotlin.String>? = null,

    /* Alternatives considered */
    @SerialName(value = "alternatives_evaluated") val alternativesEvaluated: kotlin.collections.List<kotlin.String>? = null

) {


}
