/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for DSAR status check.
 *
 * @param requestId DSAR request identifier
 * @param userId User identifier
 * @param status Request status
 * @param message Status message
 */
@Serializable

data class DSARStatusResponse (

    /* DSAR request identifier */
    @SerialName(value = "request_id") @Required val requestId: kotlin.String,

    /* User identifier */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* Request status */
    @SerialName(value = "status") @Required val status: kotlin.String,

    /* Status message */
    @SerialName(value = "message") @Required val message: kotlin.String

) {


}
