/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for DSAR initiation.
 *
 * @param requestId DSAR request identifier
 * @param userId User identifier
 * @param requestType Type of DSAR request
 * @param status Request status
 * @param exportData Exported data
 */
@Serializable

data class DSARInitiateResponse (

    /* DSAR request identifier */
    @SerialName(value = "request_id") @Required val requestId: kotlin.String,

    /* User identifier */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* Type of DSAR request */
    @SerialName(value = "request_type") @Required val requestType: kotlin.String,

    /* Request status */
    @SerialName(value = "status") @Required val status: kotlin.String,

    /* Exported data */
    @SerialName(value = "export_data") @Required val exportData: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {


}
