/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Schema for Data Subject Access Request.
 *
 * @param requestType Type of request: access, delete, export, or correct
 * @param email Contact email for the request
 * @param userIdentifier
 * @param details
 * @param urgent Whether this is an urgent request
 */
@Serializable

data class DSARRequest (

    /* Type of request: access, delete, export, or correct */
    @SerialName(value = "request_type") @Required val requestType: kotlin.String,

    /* Contact email for the request */
    @SerialName(value = "email") @Required val email: kotlin.String,

    @SerialName(value = "user_identifier") val userIdentifier: kotlin.String? = null,

    @SerialName(value = "details") val details: kotlin.String? = null,

    /* Whether this is an urgent request */
    @SerialName(value = "urgent") val urgent: kotlin.Boolean? = false

) {


}
