/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*

/**
 * Types of emergency commands.
 *
 * Values: SHUTDOWN_NOW,FREEZE,SAFE_MODE
 */
@Serializable
enum class EmergencyCommandType(val value: kotlin.String) {

    @SerialName(value = "SHUTDOWN_NOW")
    SHUTDOWN_NOW("SHUTDOWN_NOW"),

    @SerialName(value = "FREEZE")
    FREEZE("FREEZE"),

    @SerialName(value = "SAFE_MODE")
    SAFE_MODE("SAFE_MODE");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EmergencyCommandType) "$data" else null

        /**
         * Returns a valid [EmergencyCommandType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EmergencyCommandType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
