/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Result from Principled Decision Making Algorithm (PDMA).  PDMA identifies stakeholders affected by the thought and potential conflicts between their interests to inform ethical action selection.
 *
 * @param stakeholders Comma-separated list of all stakeholders who could possibly be affected by the agent's action or inaction (e.g., 'user, community, system, third-parties')
 * @param conflicts Comma-separated list of potential conflicts between stakeholder interests (e.g., 'user privacy vs system learning, individual benefit vs community harm'). Use 'none' if no conflicts identified.
 * @param reasoning Ethical reasoning for the identified stakeholders and conflicts
 * @param alignmentCheck Detailed ethical analysis addressing each CIRIS principle
 */
@Serializable

data class EthicalDMAResult (

    /* Comma-separated list of all stakeholders who could possibly be affected by the agent's action or inaction (e.g., 'user, community, system, third-parties') */
    @SerialName(value = "stakeholders") @Required val stakeholders: kotlin.String,

    /* Comma-separated list of potential conflicts between stakeholder interests (e.g., 'user privacy vs system learning, individual benefit vs community harm'). Use 'none' if no conflicts identified. */
    @SerialName(value = "conflicts") @Required val conflicts: kotlin.String,

    /* Ethical reasoning for the identified stakeholders and conflicts */
    @SerialName(value = "reasoning") @Required val reasoning: kotlin.String,

    /* Detailed ethical analysis addressing each CIRIS principle */
    @SerialName(value = "alignment_check") @Required val alignmentCheck: kotlin.String

) {


}
