/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to verify a Google Play purchase.
 *
 * @param purchaseToken Google Play purchase token
 * @param productId Product SKU (e.g., 'credits_100')
 * @param packageName App package name
 */
@Serializable

data class GooglePlayVerifyRequest (

    /* Google Play purchase token */
    @SerialName(value = "purchase_token") @Required val purchaseToken: kotlin.String,

    /* Product SKU (e.g., 'credits_100') */
    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    /* App package name */
    @SerialName(value = "package_name") @Required val packageName: kotlin.String

) {


}
