/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Base typed attributes for graph nodes.
 *
 * @param createdBy Who created this node
 * @param createdAt
 * @param updatedAt
 * @param content
 * @param tags Tags for categorization
 */
@Serializable

data class GraphNodeAttributes (

    /* Who created this node */
    @SerialName(value = "created_by") @Required val createdBy: kotlin.String,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "content") val content: kotlin.String? = null,

    /* Tags for categorization */
    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null

) {


}
