/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Typed result from all handlers.
 *
 * @param success Whether the handler succeeded
 * @param message
 * @param `data`
 * @param error
 */
@Serializable

data class HandlerResult (

    /* Whether the handler succeeded */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    @SerialName(value = "message") val message: kotlin.String? = null,

    @SerialName(value = "data") val `data`: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null,

    @SerialName(value = "error") val error: kotlin.String? = null

) {


}
