/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Image payload for multimodal requests.
 *
 * @param `data` Base64-encoded image data or URL
 * @param mediaType MIME type (image/jpeg, image/png, etc)
 * @param filename
 */
@Serializable

data class ImagePayload (

    /* Base64-encoded image data or URL */
    @SerialName(value = "data") @Required val `data`: kotlin.String,

    /* MIME type (image/jpeg, image/png, etc) */
    @SerialName(value = "media_type") val mediaType: kotlin.String? = "image/jpeg",

    @SerialName(value = "filename") val filename: kotlin.String? = null

) {


}
