/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from agent interaction.
 *
 * @param messageId Unique message ID
 * @param response Agent's response
 * @param state Agent's cognitive state after processing
 * @param processingTimeMs Time taken to process
 */
@Serializable

data class InteractResponse (

    /* Unique message ID */
    @SerialName(value = "message_id") @Required val messageId: kotlin.String,

    /* Agent's response */
    @SerialName(value = "response") @Required val response: kotlin.String,

    /* Agent's cognitive state after processing */
    @SerialName(value = "state") @Required val state: kotlin.String,

    /* Time taken to process */
    @SerialName(value = "processing_time_ms") @Required val processingTimeMs: kotlin.Int

) {


}
