/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.DocumentPayload
import ai.ciris.api.models.ImagePayload
import ai.ciris.api.models.MessageContext

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to interact with the agent.
 *
 * @param message Message to send to the agent
 * @param context
 * @param images
 * @param documents
 */
@Serializable

data class InteractRequest (

    /* Message to send to the agent */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "context") val context: MessageContext? = null,

    @SerialName(value = "images") val images: kotlin.collections.List<ImagePayload>? = null,

    @SerialName(value = "documents") val documents: kotlin.collections.List<DocumentPayload>? = null

) {


}
