/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ModelCapabilities

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A model returned from a provider's live API, annotated with CIRIS compatibility.
 *
 * @param id Model ID as returned by the provider
 * @param displayName Human-readable name (from capabilities DB or derived)
 * @param cirisCompatible
 * @param cirisRecommended Whether CIRIS recommends this model
 * @param tier
 * @param capabilities
 * @param contextWindow
 * @param notes
 * @param source Data source: 'live', 'static', or 'both'
 */
@Serializable

data class LiveModelInfo (

    /* Model ID as returned by the provider */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* Human-readable name (from capabilities DB or derived) */
    @SerialName(value = "display_name") @Required val displayName: kotlin.String,

    @SerialName(value = "ciris_compatible") val cirisCompatible: kotlin.Boolean? = null,

    /* Whether CIRIS recommends this model */
    @SerialName(value = "ciris_recommended") val cirisRecommended: kotlin.Boolean? = false,

    @SerialName(value = "tier") val tier: kotlin.String? = null,

    @SerialName(value = "capabilities") val capabilities: ModelCapabilities? = null,

    @SerialName(value = "context_window") val contextWindow: kotlin.Int? = null,

    @SerialName(value = "notes") val notes: kotlin.String? = null,

    /* Data source: 'live', 'static', or 'both' */
    @SerialName(value = "source") val source: kotlin.String? = "live"

) {


}
