/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from LLM validation.
 *
 * @param valid Whether configuration is valid
 * @param message Validation message
 * @param error
 */
@Serializable

data class LLMValidationResponse (

    /* Whether configuration is valid */
    @SerialName(value = "valid") @Required val valid: kotlin.Boolean,

    /* Validation message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "error") val error: kotlin.String? = null

) {


}
