/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to authenticate with username/password.
 *
 * @param username Username
 * @param password Password
 */
@Serializable

data class LoginRequest (

    /* Username */
    @SerialName(value = "username") @Required val username: kotlin.String,

    /* Password */
    @SerialName(value = "password") @Required val password: kotlin.String

) {


}
