/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*

/**
 * Status of a memory operation.
 *
 * Values: OK,OK2,DEFERRED,DENIED,PENDING,ERROR,ERROR2
 */
@Serializable
enum class MemoryOpStatus(val value: kotlin.String) {

    @SerialName(value = "ok")
    OK("ok"),

    @SerialName(value = "ok_2")
    OK2("ok"),

    @SerialName(value = "deferred")
    DEFERRED("deferred"),

    @SerialName(value = "denied")
    DENIED("denied"),

    @SerialName(value = "pending")
    PENDING("pending"),

    @SerialName(value = "error")
    ERROR("error"),

    @SerialName(value = "error_2")
    ERROR2("error");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is MemoryOpStatus) "$data" else null

        /**
         * Returns a valid [MemoryOpStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): MemoryOpStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
