/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.MessageRejectionReason

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from message submission (returns immediately with task ID or rejection reason).
 *
 * @param messageId Unique message ID for tracking
 * @param channelId Channel where message was sent
 * @param submittedAt ISO timestamp of submission
 * @param accepted Whether message was accepted for processing
 * @param taskId
 * @param rejectionReason
 * @param rejectionDetail
 */
@Serializable

data class MessageSubmissionResponse (

    /* Unique message ID for tracking */
    @SerialName(value = "message_id") @Required val messageId: kotlin.String,

    /* Channel where message was sent */
    @SerialName(value = "channel_id") @Required val channelId: kotlin.String,

    /* ISO timestamp of submission */
    @SerialName(value = "submitted_at") @Required val submittedAt: kotlin.String,

    /* Whether message was accepted for processing */
    @SerialName(value = "accepted") @Required val accepted: kotlin.Boolean,

    @SerialName(value = "task_id") val taskId: kotlin.String? = null,

    @SerialName(value = "rejection_reason") val rejectionReason: MessageRejectionReason? = null,

    @SerialName(value = "rejection_detail") val rejectionDetail: kotlin.String? = null

) {


}
