/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Aggregated metric statistics.
 *
 * @param min Minimum value
 * @param max Maximum value
 * @param avg Average value
 * @param sum Sum of values
 * @param count Number of data points
 * @param p50
 * @param p95
 * @param p99
 */
@Serializable

data class MetricAggregate (

    /* Minimum value */
    @SerialName(value = "min") val min: kotlin.Double? = (0.0).toDouble(),

    /* Maximum value */
    @SerialName(value = "max") val max: kotlin.Double? = (0.0).toDouble(),

    /* Average value */
    @SerialName(value = "avg") val avg: kotlin.Double? = (0.0).toDouble(),

    /* Sum of values */
    @SerialName(value = "sum") val sum: kotlin.Double? = (0.0).toDouble(),

    /* Number of data points */
    @SerialName(value = "count") val count: kotlin.Int? = 0,

    @SerialName(value = "p50") val p50: kotlin.Double? = null,

    @SerialName(value = "p95") val p95: kotlin.Double? = null,

    @SerialName(value = "p99") val p99: kotlin.Double? = null

) {


}
