/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.WARole

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to mint user as Wise Authority.
 *
 * @param waRole Role to grant: AUTHORITY or OBSERVER
 * @param signature
 * @param privateKeyPath
 */
@Serializable

data class MintWARequest (

    /* Role to grant: AUTHORITY or OBSERVER */
    @SerialName(value = "wa_role") @Required val waRole: WARole,

    @SerialName(value = "signature") val signature: kotlin.String? = null,

    @SerialName(value = "private_key_path") val privateKeyPath: kotlin.String? = null

) {


}
