/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Capabilities flags for an LLM model.
 *
 * @param toolUse Native function/tool calling support
 * @param structuredOutput Reliable JSON output for tool calls
 * @param vision Image/multimodal input support
 * @param jsonMode JSON mode for structured responses
 * @param streaming Streaming response support
 */
@Serializable

data class ModelCapabilities (

    /* Native function/tool calling support */
    @SerialName(value = "tool_use") @Required val toolUse: kotlin.Boolean,

    /* Reliable JSON output for tool calls */
    @SerialName(value = "structured_output") @Required val structuredOutput: kotlin.Boolean,

    /* Image/multimodal input support */
    @SerialName(value = "vision") val vision: kotlin.Boolean? = false,

    /* JSON mode for structured responses */
    @SerialName(value = "json_mode") val jsonMode: kotlin.Boolean? = false,

    /* Streaming response support */
    @SerialName(value = "streaming") val streaming: kotlin.Boolean? = true

) {


}
