/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 * MANUALLY MODIFIED: This file handles dynamic metadata values that can be
 * any JSON type (string, boolean, number, object, array, null).
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * Metadata value - can be any JSON type (string, boolean, number, object, array).
 * Wraps JsonElement to handle dynamic metadata from the API.
 */
@Serializable(with = ModuleTypeInfoMetadataValueSerializer::class)
data class ModuleTypeInfoMetadataValue(
    val value: JsonElement
) {
    /**
     * Get the value as a string, or null if not a string primitive.
     */
    fun asStringOrNull(): String? = (value as? JsonPrimitive)?.contentOrNull

    /**
     * Get the value as a boolean, or null if not a boolean primitive.
     */
    fun asBooleanOrNull(): Boolean? = (value as? JsonPrimitive)?.booleanOrNull

    /**
     * Get the value as an int, or null if not an integer primitive.
     */
    fun asIntOrNull(): Int? = (value as? JsonPrimitive)?.intOrNull

    override fun toString(): String = value.toString()
}

/**
 * Custom serializer for ModuleTypeInfoMetadataValue that handles any JSON value type.
 */
object ModuleTypeInfoMetadataValueSerializer : KSerializer<ModuleTypeInfoMetadataValue> {
    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor

    override fun serialize(encoder: Encoder, value: ModuleTypeInfoMetadataValue) {
        encoder.encodeSerializableValue(JsonElement.serializer(), value.value)
    }

    override fun deserialize(decoder: Decoder): ModuleTypeInfoMetadataValue {
        val element = decoder.decodeSerializableValue(JsonElement.serializer())
        return ModuleTypeInfoMetadataValue(element)
    }
}
