/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * OAuth provider information.
 *
 * @param provider Provider name
 * @param clientId OAuth client ID
 * @param callbackUrl OAuth callback URL
 * @param created
 * @param metadata Additional metadata
 */
@Serializable

data class OAuthProviderInfo (

    /* Provider name */
    @SerialName(value = "provider") @Required val provider: kotlin.String,

    /* OAuth client ID */
    @SerialName(value = "client_id") @Required val clientId: kotlin.String,

    /* OAuth callback URL */
    @SerialName(value = "callback_url") @Required val callbackUrl: kotlin.String,

    @SerialName(value = "created") val created: kotlin.String? = null,

    /* Additional metadata */
    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}
