/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 * MANUALLY MODIFIED: This file handles dynamic values that can be
 * any JSON type (string, boolean, number, object, array, null).
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.*

/**
 * Dynamic value wrapper - can be any JSON type.
 * Used for tool/function parameter values.
 */
@Serializable(with = ParametersValueSerializer::class)
data class ParametersValue(
    val value: JsonElement
) {
    fun asStringOrNull(): String? = (value as? JsonPrimitive)?.contentOrNull
    fun asBooleanOrNull(): Boolean? = (value as? JsonPrimitive)?.booleanOrNull
    fun asIntOrNull(): Int? = (value as? JsonPrimitive)?.intOrNull
    override fun toString(): String = value.toString()
}

object ParametersValueSerializer : KSerializer<ParametersValue> {
    override val descriptor: SerialDescriptor = JsonElement.serializer().descriptor

    override fun serialize(encoder: Encoder, value: ParametersValue) {
        encoder.encodeSerializableValue(JsonElement.serializer(), value.value)
    }

    override fun deserialize(decoder: Decoder): ParametersValue {
        val element = decoder.decodeSerializableValue(JsonElement.serializer())
        return ParametersValue(element)
    }
}
