/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A deferral awaiting WA review.
 *
 * @param deferralId Unique deferral identifier
 * @param createdAt When deferral was created
 * @param deferredBy Agent that deferred
 * @param taskId Associated task ID
 * @param thoughtId Associated thought ID
 * @param reason Reason for deferral
 * @param channelId
 * @param userId
 * @param priority Deferral priority
 * @param assignedWaId
 * @param requiresRole
 * @param status Current status
 * @param resolution
 * @param resolvedAt
 * @param question
 * @param context Additional context for UI
 * @param timeoutAt
 */
@Serializable

data class PendingDeferral (

    /* Unique deferral identifier */
    @SerialName(value = "deferral_id") @Required val deferralId: kotlin.String,

    /* When deferral was created */
    @SerialName(value = "created_at") @Required val createdAt: kotlinx.datetime.Instant,

    /* Agent that deferred */
    @SerialName(value = "deferred_by") @Required val deferredBy: kotlin.String,

    /* Associated task ID */
    @SerialName(value = "task_id") @Required val taskId: kotlin.String,

    /* Associated thought ID */
    @SerialName(value = "thought_id") @Required val thoughtId: kotlin.String,

    /* Reason for deferral */
    @SerialName(value = "reason") @Required val reason: kotlin.String,

    @SerialName(value = "channel_id") val channelId: kotlin.String? = null,

    @SerialName(value = "user_id") val userId: kotlin.String? = null,

    /* Deferral priority */
    @SerialName(value = "priority") val priority: kotlin.String? = "normal",

    @SerialName(value = "assigned_wa_id") val assignedWaId: kotlin.String? = null,

    @SerialName(value = "requires_role") val requiresRole: kotlin.String? = null,

    /* Current status */
    @SerialName(value = "status") val status: kotlin.String? = "pending",

    @SerialName(value = "resolution") val resolution: kotlin.String? = null,

    @SerialName(value = "resolved_at") val resolvedAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "question") val question: kotlin.String? = null,

    /* Additional context for UI */
    @SerialName(value = "context") val context: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "timeout_at") val timeoutAt: kotlin.String? = null

) {


}
