/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for permission request operation.
 *
 * @param success Whether the request was successful
 * @param status Status of the request (already_granted, already_requested, request_submitted)
 * @param message Human-readable message
 * @param requestedAt
 */
@Serializable

data class PermissionRequestResponse (

    /* Whether the request was successful */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    /* Status of the request (already_granted, already_requested, request_submitted) */
    @SerialName(value = "status") @Required val status: kotlin.String,

    /* Human-readable message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "requested_at") val requestedAt: kotlinx.datetime.Instant? = null

) {


}
