/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for persisted adapter configurations.
 *
 * @param count Number of persisted configurations
 * @param persistedConfigs Map of adapter_type to configuration data
 */
@Serializable

data class PersistedConfigsResponse (

    /* Number of persisted configurations */
    @SerialName(value = "count") @Required val count: kotlin.Int,

    /* Map of adapter_type to configuration data */
    @SerialName(value = "persisted_configs") val persistedConfigs: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>>? = null

) {


}
