/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Purchase status response.
 *
 * @param status Payment status (succeeded, pending, failed)
 * @param creditsAdded Credits added (0 if not completed)
 * @param balanceAfter
 */
@Serializable

data class PurchaseStatusResponse (

    /* Payment status (succeeded, pending, failed) */
    @SerialName(value = "status") @Required val status: kotlin.String,

    /* Credits added (0 if not completed) */
    @SerialName(value = "credits_added") @Required val creditsAdded: kotlin.Int,

    @SerialName(value = "balance_after") val balanceAfter: kotlin.Int? = null

) {


}
