/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.GraphScope

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Parameters for RECALL action.
 *
 * @param channelId
 * @param query
 * @param nodeType
 * @param nodeId
 * @param scope
 * @param limit Maximum number of results
 */
@Serializable

data class RecallParams (

    @SerialName(value = "channel_id") val channelId: kotlin.String? = null,

    @SerialName(value = "query") val query: kotlin.String? = null,

    @SerialName(value = "node_type") val nodeType: kotlin.String? = null,

    @SerialName(value = "node_id") val nodeId: kotlin.String? = null,

    @SerialName(value = "scope") val scope: GraphScope? = null,

    /* Maximum number of results */
    @SerialName(value = "limit") val limit: kotlin.Int? = 10

) {


}
