/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for removing a persisted configuration.
 *
 * @param success Whether the removal succeeded
 * @param adapterType Adapter type that was removed
 * @param message Status message
 */
@Serializable

data class RemovePersistedResponse (

    /* Whether the removal succeeded */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    /* Adapter type that was removed */
    @SerialName(value = "adapter_type") @Required val adapterType: kotlin.String,

    /* Status message */
    @SerialName(value = "message") @Required val message: kotlin.String

) {


}
