/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResourceHealthStatus
import ai.ciris.api.models.ResourceHistoryPoint
import ai.ciris.api.models.ResourceLimits
import ai.ciris.api.models.ResourceUsageData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Complete resource telemetry response.
 *
 * @param current Current resource usage
 * @param limits Resource limits
 * @param health Health status
 * @param history Historical data
 */
@Serializable

data class ResourceTelemetryResponse (

    /* Current resource usage */
    @SerialName(value = "current") @Required val current: ResourceUsageData,

    /* Resource limits */
    @SerialName(value = "limits") @Required val limits: ResourceLimits,

    /* Health status */
    @SerialName(value = "health") @Required val health: ResourceHealthStatus,

    /* Historical data */
    @SerialName(value = "history") val history: kotlin.collections.List<ResourceHistoryPoint>? = null

) {


}
