/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResourceBudget
import ai.ciris.api.models.ResourceSnapshot

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * System resource usage and limits.
 *
 * @param currentUsage Current resource usage
 * @param limits Configured resource limits
 * @param healthStatus Resource health (healthy/warning/critical)
 * @param warnings Resource warnings
 * @param critical Critical resource issues
 */
@Serializable

data class ResourceUsageResponse (

    /* Current resource usage */
    @SerialName(value = "current_usage") @Required val currentUsage: ResourceSnapshot,

    /* Configured resource limits */
    @SerialName(value = "limits") @Required val limits: ResourceBudget,

    /* Resource health (healthy/warning/critical) */
    @SerialName(value = "health_status") @Required val healthStatus: kotlin.String,

    /* Resource warnings */
    @SerialName(value = "warnings") val warnings: kotlin.collections.List<kotlin.String>? = null,

    /* Critical resource issues */
    @SerialName(value = "critical") val critical: kotlin.collections.List<kotlin.String>? = null

) {


}
