/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResourceLimit

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Limits for all monitored resources
 *
 * @param memoryMb Memory usage limits in MB
 * @param cpuPercent CPU usage limits in percent
 * @param tokensHour Token usage per hour
 * @param tokensDay Token usage per day
 * @param diskMb Disk usage limits in MB
 * @param thoughtsActive Active thoughts limit
 */
@Serializable

data class ResourceBudget (

    /* Memory usage limits in MB */
    @SerialName(value = "memory_mb") val memoryMb: ResourceLimit? = null,

    /* CPU usage limits in percent */
    @SerialName(value = "cpu_percent") val cpuPercent: ResourceLimit? = null,

    /* Token usage per hour */
    @SerialName(value = "tokens_hour") val tokensHour: ResourceLimit? = null,

    /* Token usage per day */
    @SerialName(value = "tokens_day") val tokensDay: ResourceLimit? = null,

    /* Disk usage limits in MB */
    @SerialName(value = "disk_mb") val diskMb: ResourceLimit? = null,

    /* Active thoughts limit */
    @SerialName(value = "thoughts_active") val thoughtsActive: ResourceLimit? = null

) {


}
