/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Resource usage limits.
 *
 * @param maxMemoryMb Maximum memory in MB
 * @param maxCpuPercent Maximum CPU percentage
 * @param maxDiskBytes Maximum disk usage in bytes
 */
@Serializable

data class ResourceLimits (

    /* Maximum memory in MB */
    @SerialName(value = "max_memory_mb") @Required val maxMemoryMb: kotlin.Double,

    /* Maximum CPU percentage */
    @SerialName(value = "max_cpu_percent") val maxCpuPercent: kotlin.Double? = (100.0).toDouble(),

    /* Maximum disk usage in bytes */
    @SerialName(value = "max_disk_bytes") val maxDiskBytes: kotlin.Int? = 0

) {


}
