/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to resolve a deferral with integrated guidance.
 *
 * @param resolution Resolution type
 * @param guidance WA wisdom guidance integrated with the decision
 */
@Serializable

data class ResolveDeferralRequest (

    /* Resolution type */
    @SerialName(value = "resolution") @Required val resolution: kotlin.String,

    /* WA wisdom guidance integrated with the decision */
    @SerialName(value = "guidance") @Required val guidance: kotlin.String

) {


}
