/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Current resource usage data.
 *
 * @param cpuPercent CPU usage percentage
 * @param memoryMb Memory usage in MB
 * @param memoryPercent Memory usage percentage
 * @param timestamp Timestamp of measurement
 * @param diskUsageBytes Disk usage in bytes
 * @param diskUsageGb Disk usage in GB
 * @param activeThreads Number of active threads
 * @param openFiles Number of open files
 */
@Serializable

data class ResourceUsageData (

    /* CPU usage percentage */
    @SerialName(value = "cpu_percent") @Required val cpuPercent: kotlin.Double,

    /* Memory usage in MB */
    @SerialName(value = "memory_mb") @Required val memoryMb: kotlin.Double,

    /* Memory usage percentage */
    @SerialName(value = "memory_percent") @Required val memoryPercent: kotlin.Double,

    /* Timestamp of measurement */
    @SerialName(value = "timestamp") @Required val timestamp: kotlin.String,

    /* Disk usage in bytes */
    @SerialName(value = "disk_usage_bytes") val diskUsageBytes: kotlin.Int? = 0,

    /* Disk usage in GB */
    @SerialName(value = "disk_usage_gb") val diskUsageGb: kotlin.Double? = (0.0).toDouble(),

    /* Number of active threads */
    @SerialName(value = "active_threads") val activeThreads: kotlin.Int? = 0,

    /* Number of open files */
    @SerialName(value = "open_files") val openFiles: kotlin.Int? = 0

) {


}
