/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.AdapterMetrics
import ai.ciris.api.models.CirisEngineSchemasRuntimeAdapterManagementAdapterConfig
import ai.ciris.api.models.ToolInfo

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Status of a single adapter.
 *
 * @param adapterId Unique Adapter ID
 * @param adapterType Type of adapter
 * @param isRunning Whether adapter is running
 * @param loadedAt
 * @param servicesRegistered Services registered by adapter
 * @param configParams
 * @param metrics
 * @param lastActivity
 * @param tools
 */
@Serializable

data class RuntimeAdapterStatus (

    /* Unique Adapter ID */
    @SerialName(value = "adapter_id") @Required val adapterId: kotlin.String,

    /* Type of adapter */
    @SerialName(value = "adapter_type") @Required val adapterType: kotlin.String,

    /* Whether adapter is running */
    @SerialName(value = "is_running") @Required val isRunning: kotlin.Boolean,

    @SerialName(value = "loaded_at") val loadedAt: kotlinx.datetime.Instant? = null,

    /* Services registered by adapter */
    @SerialName(value = "services_registered") val servicesRegistered: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "config_params") val configParams: CirisEngineSchemasRuntimeAdapterManagementAdapterConfig? = null,

    @SerialName(value = "metrics") val metrics: AdapterMetrics? = null,

    @SerialName(value = "last_activity") val lastActivity: kotlinx.datetime.Instant? = null,

    @SerialName(value = "tools") val tools: kotlin.collections.List<ToolInfo>? = null,

    /* Error message if adapter failed */
    @SerialName(value = "error") val error: kotlin.String? = null,

    /* Whether re-authentication is required */
    @SerialName(value = "needs_reauth") val needsReauth: kotlin.Boolean = false,

    /* Reason re-authentication is needed */
    @SerialName(value = "reauth_reason") val reauthReason: kotlin.String? = null,

    /* Whether adapter has an auth step in its wizard */
    @SerialName(value = "has_auth_step") val hasAuthStep: kotlin.Boolean = false,

    /* ID of the auth step (oauth or device_auth) */
    @SerialName(value = "auth_step_id") val authStepId: kotlin.String? = null

) {


}
