/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ServiceDetailsValueValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Health status of services.
 *
 * @param overallHealth Overall health: healthy, degraded, unhealthy
 * @param healthyServices Number of healthy services
 * @param unhealthyServices Number of unhealthy services
 * @param serviceDetails Per-service health details
 * @param timestamp
 * @param recommendations Health recommendations
 */
@Serializable

data class ServiceHealthStatus (

    /* Overall health: healthy, degraded, unhealthy */
    @SerialName(value = "overall_health") @Required val overallHealth: kotlin.String,

    /* Number of healthy services */
    @SerialName(value = "healthy_services") @Required val healthyServices: kotlin.Int,

    /* Number of unhealthy services */
    @SerialName(value = "unhealthy_services") @Required val unhealthyServices: kotlin.Int,

    /* Per-service health details */
    @SerialName(value = "service_details") @Required val serviceDetails: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, ServiceDetailsValueValue>>,

    @SerialName(value = "timestamp") val timestamp: kotlinx.datetime.Instant? = null,

    /* Health recommendations */
    @SerialName(value = "recommendations") val recommendations: kotlin.collections.List<kotlin.String>? = null

) {


}
