/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ServiceMetrics

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Individual service status.
 *
 * @param name Service name
 * @param type Service type
 * @param healthy Whether service is healthy
 * @param available Whether service is available
 * @param uptimeSeconds
 * @param metrics Service-specific metrics
 */
@Serializable

data class ServiceStatus (

    /* Service name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Service type */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* Whether service is healthy */
    @SerialName(value = "healthy") @Required val healthy: kotlin.Boolean,

    /* Whether service is available */
    @SerialName(value = "available") @Required val available: kotlin.Boolean,

    @SerialName(value = "uptime_seconds") val uptimeSeconds: kotlin.Double? = null,

    /* Service-specific metrics */
    @SerialName(value = "metrics") val metrics: ServiceMetrics? = null

) {


}
