/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ServiceSelectionExplanationPrioritiesValueValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Explanation of service selection logic.
 *
 * @param overview Overview of selection logic
 * @param priorityGroups Priority group explanations
 * @param selectionStrategies Strategy explanations
 * @param examples Example scenarios
 * @param configurationTips Configuration recommendations
 * @param priorities
 * @param selectionFlow
 * @param circuitBreakerInfo
 */
@Serializable

data class ServiceSelectionExplanation (

    /* Overview of selection logic */
    @SerialName(value = "overview") @Required val overview: kotlin.String,

    /* Priority group explanations */
    @SerialName(value = "priority_groups") @Required val priorityGroups: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* Strategy explanations */
    @SerialName(value = "selection_strategies") @Required val selectionStrategies: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* Example scenarios */
    @SerialName(value = "examples") @Required val examples: kotlin.collections.List<@Contextual kotlin.collections.Map<kotlin.String, ServiceSelectionExplanationPrioritiesValueValue>>,

    /* Configuration recommendations */
    @SerialName(value = "configuration_tips") @Required val configurationTips: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "priorities") val priorities: kotlin.collections.Map<kotlin.String, kotlin.collections.Map<kotlin.String, ServiceSelectionExplanationPrioritiesValueValue>>? = null,

    @SerialName(value = "selection_flow") val selectionFlow: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "circuit_breaker_info") val circuitBreakerInfo: kotlin.collections.Map<kotlin.String, ServiceSelectionExplanationPrioritiesValueValue>? = null

) {


}
