/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response from service priority update.
 *
 * @param providerName Provider name that was updated
 * @param oldPriority Previous priority level
 * @param newPriority New priority level
 * @param message Status message
 * @param oldPriorityGroup
 * @param newPriorityGroup
 * @param oldStrategy
 * @param newStrategy
 */
@Serializable

data class ServicePriorityUpdateResponse (

    /* Provider name that was updated */
    @SerialName(value = "provider_name") @Required val providerName: kotlin.String,

    /* Previous priority level */
    @SerialName(value = "old_priority") @Required val oldPriority: kotlin.String,

    /* New priority level */
    @SerialName(value = "new_priority") @Required val newPriority: kotlin.String,

    /* Status message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    @SerialName(value = "old_priority_group") val oldPriorityGroup: kotlin.Int? = null,

    @SerialName(value = "new_priority_group") val newPriorityGroup: kotlin.Int? = null,

    @SerialName(value = "old_strategy") val oldStrategy: kotlin.String? = null,

    @SerialName(value = "new_strategy") val newStrategy: kotlin.String? = null

) {


}
