/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Service-specific metrics.
 *
 * @param uptimeSeconds
 * @param requestsHandled
 * @param errorCount
 * @param avgResponseTimeMs
 * @param memoryMb
 * @param customMetrics
 */
@Serializable

data class ServiceMetrics (

    @SerialName(value = "uptime_seconds") val uptimeSeconds: kotlin.Double? = null,

    @SerialName(value = "requests_handled") val requestsHandled: kotlin.Int? = null,

    @SerialName(value = "error_count") val errorCount: kotlin.Int? = null,

    @SerialName(value = "avg_response_time_ms") val avgResponseTimeMs: kotlin.Double? = null,

    @SerialName(value = "memory_mb") val memoryMb: kotlin.Double? = null,

    @SerialName(value = "custom_metrics") val customMetrics: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null

) {


}
