/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Setup status information.
 *
 * @param isFirstRun Whether this is first run
 * @param configExists Whether config file exists
 * @param setupRequired Whether setup is required
 * @param configPath
 */
@Serializable

data class SetupStatusResponse (

    /* Whether this is first run */
    @SerialName(value = "is_first_run") @Required val isFirstRun: kotlin.Boolean,

    /* Whether config file exists */
    @SerialName(value = "config_exists") @Required val configExists: kotlin.Boolean,

    /* Whether setup is required */
    @SerialName(value = "setup_required") @Required val setupRequired: kotlin.Boolean,

    @SerialName(value = "config_path") val configPath: kotlin.String? = null

) {


}
