/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Graceful shutdown request.
 *
 * @param reason Reason for shutdown
 * @param confirm Confirmation flag (must be true)
 * @param force Force immediate shutdown
 */
@Serializable

data class ShutdownRequest (

    /* Reason for shutdown */
    @SerialName(value = "reason") @Required val reason: kotlin.String,

    /* Confirmation flag (must be true) */
    @SerialName(value = "confirm") @Required val confirm: kotlin.Boolean,

    /* Force immediate shutdown */
    @SerialName(value = "force") val force: kotlin.Boolean? = false

) {


}
