/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.PipelineState
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue
import ai.ciris.api.models.StepPoint

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for single-step operations with detailed step point data.  Extends the basic RuntimeControlResponse with comprehensive step point information, pipeline state, and demo-ready data for transparent AI operation visibility.
 *
 * @param success Whether action succeeded
 * @param message Human-readable status message
 * @param processorState Current processor state
 * @param cognitiveState
 * @param queueDepth Number of items in processing queue
 * @param stepPoint
 * @param stepResult
 * @param pipelineState
 * @param processingTimeMs Total processing time for this step in milliseconds
 * @param tokensUsed
 * @param transparencyData
 */
@Serializable

data class SingleStepResponse (

    /* Whether action succeeded */
    @SerialName(value = "success") @Required val success: kotlin.Boolean,

    /* Human-readable status message */
    @SerialName(value = "message") @Required val message: kotlin.String,

    /* Current processor state */
    @SerialName(value = "processor_state") @Required val processorState: kotlin.String,

    @SerialName(value = "cognitive_state") val cognitiveState: kotlin.String? = null,

    /* Number of items in processing queue */
    @SerialName(value = "queue_depth") val queueDepth: kotlin.Int? = 0,

    @SerialName(value = "step_point") val stepPoint: StepPoint? = null,

    @SerialName(value = "step_result") val stepResult: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null,

    @SerialName(value = "pipeline_state") val pipelineState: PipelineState? = null,

    /* Total processing time for this step in milliseconds */
    @SerialName(value = "processing_time_ms") val processingTimeMs: kotlin.Double? = (0.0).toDouble(),

    @SerialName(value = "tokens_used") val tokensUsed: kotlin.Int? = null,

    @SerialName(value = "transparency_data") val transparencyData: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null

) {


}
