/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to execute a configuration step.
 *
 * @param stepData Data for step execution
 */
@Serializable

data class StepExecutionRequest (

    /* Data for step execution */
    @SerialName(value = "step_data") val stepData: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null

) {


}
