/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*

/**
 * Points where single-stepping can pause in the H3ERE pipeline.
 *
 * Values: START_ROUND,GATHER_CONTEXT,PERFORM_DMAS,PERFORM_ASPDMA,CONSCIENCE_EXECUTION,RECURSIVE_ASPDMA,RECURSIVE_CONSCIENCE,FINALIZE_ACTION,PERFORM_ACTION,ACTION_COMPLETE,ROUND_COMPLETE
 */
@Serializable
enum class StepPoint(val value: kotlin.String) {

    @SerialName(value = "start_round")
    START_ROUND("start_round"),

    @SerialName(value = "gather_context")
    GATHER_CONTEXT("gather_context"),

    @SerialName(value = "perform_dmas")
    PERFORM_DMAS("perform_dmas"),

    @SerialName(value = "perform_aspdma")
    PERFORM_ASPDMA("perform_aspdma"),

    @SerialName(value = "conscience_execution")
    CONSCIENCE_EXECUTION("conscience_execution"),

    @SerialName(value = "recursive_aspdma")
    RECURSIVE_ASPDMA("recursive_aspdma"),

    @SerialName(value = "recursive_conscience")
    RECURSIVE_CONSCIENCE("recursive_conscience"),

    @SerialName(value = "finalize_action")
    FINALIZE_ACTION("finalize_action"),

    @SerialName(value = "perform_action")
    PERFORM_ACTION("perform_action"),

    @SerialName(value = "action_complete")
    ACTION_COMPLETE("action_complete"),

    @SerialName(value = "round_complete")
    ROUND_COMPLETE("round_complete");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is StepPoint) "$data" else null

        /**
         * Returns a valid [StepPoint] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): StepPoint? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
