/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.DeferParamsContextValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Parameters for TASK_COMPLETE action.
 *
 * @param channelId
 * @param completionReason
 * @param context
 * @param positiveMoment
 * @param persistImages If True, preserve task images after completion. Default False purges images for privacy/storage.
 */
@Serializable

data class TaskCompleteParams (

    @SerialName(value = "channel_id") val channelId: kotlin.String? = null,

    @SerialName(value = "completion_reason") val completionReason: kotlin.String? = "Task completed successfully",

    @SerialName(value = "context") val context: kotlin.collections.Map<kotlin.String, DeferParamsContextValue>? = null,

    @SerialName(value = "positive_moment") val positiveMoment: kotlin.String? = null,

    /* If True, preserve task images after completion. Default False purges images for privacy/storage. */
    @SerialName(value = "persist_images") val persistImages: kotlin.Boolean? = false

) {


}
