/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.TelemetryQueryFilters

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Custom telemetry query.
 *
 * @param queryType Query type: metrics|traces|logs|incidents|insights
 * @param filters Query filters
 * @param aggregations
 * @param startTime
 * @param endTime
 * @param limit Result limit
 */
@Serializable

data class TelemetryQuery (

    /* Query type: metrics|traces|logs|incidents|insights */
    @SerialName(value = "query_type") @Required val queryType: kotlin.String,

    /* Query filters */
    @SerialName(value = "filters") val filters: TelemetryQueryFilters? = null,

    @SerialName(value = "aggregations") val aggregations: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "start_time") val startTime: kotlinx.datetime.Instant? = null,

    @SerialName(value = "end_time") val endTime: kotlinx.datetime.Instant? = null,

    /* Result limit */
    @SerialName(value = "limit") val limit: kotlin.Int? = 100

) {


}
