/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to refresh access token.
 *
 * @param refreshToken Refresh token
 */
@Serializable

data class TokenRefreshRequest (

    /* Refresh token */
    @SerialName(value = "refresh_token") @Required val refreshToken: kotlin.String

) {


}
