/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Balance information for a specific tool.
 *
 * @param productType Tool product type (e.g., 'web_search')
 * @param freeRemaining Remaining free uses
 * @param paidCredits Paid credits available
 * @param totalAvailable Total available uses (free + paid)
 * @param priceMinor Price per credit in minor units (cents)
 * @param totalUses Total lifetime uses
 */
@Serializable

data class ToolBalanceResponse (

    /* Tool product type (e.g., 'web_search') */
    @SerialName(value = "product_type") @Required val productType: kotlin.String,

    /* Remaining free uses */
    @SerialName(value = "free_remaining") @Required val freeRemaining: kotlin.Int,

    /* Paid credits available */
    @SerialName(value = "paid_credits") @Required val paidCredits: kotlin.Int,

    /* Total available uses (free + paid) */
    @SerialName(value = "total_available") @Required val totalAvailable: kotlin.Int,

    /* Price per credit in minor units (cents) */
    @SerialName(value = "price_minor") @Required val priceMinor: kotlin.Int,

    /* Total lifetime uses */
    @SerialName(value = "total_uses") @Required val totalUses: kotlin.Int

) {


}
