/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Information about an available tool.
 *
 * @param name Tool name
 * @param description Tool description
 * @param cost Cost per use in credits
 * @param available Whether tool is available on this platform
 * @param platformRequirements Platform requirements for this tool
 */
@Serializable

data class ToolInfoResponse (

    /* Tool name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Tool description */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Cost per use in credits */
    @SerialName(value = "cost") @Required val cost: kotlin.Double,

    /* Whether tool is available on this platform */
    @SerialName(value = "available") @Required val available: kotlin.Boolean,

    /* Platform requirements for this tool */
    @SerialName(value = "platform_requirements") val platformRequirements: kotlin.collections.List<kotlin.String>? = null

) {


}
