/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.PlatformRequirement
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue
import ai.ciris.api.models.ToolParameterSchema

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Information about a tool provided by an adapter.
 *
 * @param name Tool name
 * @param description What the tool does
 * @param parameters Tool parameters schema
 * @param category Tool category
 * @param cost Cost to execute the tool
 * @param whenToUse
 * @param contextEnrichment If True, tool is automatically run during context gathering to enrich ASPDMA prompt
 * @param contextEnrichmentParams
 * @param platformRequirements Platform security requirements (e.g., ANDROID_PLAY_INTEGRITY, DPOP)
 * @param platformRequirementsRationale
 */
@Serializable

data class ToolInfo (

    /* Tool name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* What the tool does */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Tool parameters schema */
    @SerialName(value = "parameters") @Required val parameters: ToolParameterSchema,

    /* Tool category */
    @SerialName(value = "category") val category: kotlin.String? = "general",

    /* Cost to execute the tool */
    @SerialName(value = "cost") val cost: kotlin.Double? = (0.0).toDouble(),

    @SerialName(value = "when_to_use") val whenToUse: kotlin.String? = null,

    /* If True, tool is automatically run during context gathering to enrich ASPDMA prompt */
    @SerialName(value = "context_enrichment") val contextEnrichment: kotlin.Boolean? = false,

    @SerialName(value = "context_enrichment_params") val contextEnrichmentParams: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null,

    /* Platform security requirements (e.g., ANDROID_PLAY_INTEGRITY, DPOP) */
    @SerialName(value = "platform_requirements") val platformRequirements: kotlin.collections.List<@Contextual PlatformRequirement>? = null,

    @SerialName(value = "platform_requirements_rationale") val platformRequirementsRationale: kotlin.String? = null

) {


}
