/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request to verify and process a tool credit purchase.
 *
 * @param productId Google Play product ID (e.g., 'web_search_10')
 * @param purchaseToken Google Play purchase token
 * @param toolName Tool to add credits to (e.g., 'web_search')
 */
@Serializable

data class ToolPurchaseRequest (

    /* Google Play product ID (e.g., 'web_search_10') */
    @SerialName(value = "product_id") @Required val productId: kotlin.String,

    /* Google Play purchase token */
    @SerialName(value = "purchase_token") @Required val purchaseToken: kotlin.String,

    /* Tool to add credits to (e.g., 'web_search') */
    @SerialName(value = "tool_name") @Required val toolName: kotlin.String

) {


}
