/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.CompleteTraceResponse

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List of captured traces.
 *
 * @param traces Captured traces
 * @param total Total trace count
 * @param consentGiven Whether metrics consent is active
 */
@Serializable

data class TracesListResponse (

    /* Captured traces */
    @SerialName(value = "traces") @Required val traces: kotlin.collections.List<CompleteTraceResponse>,

    /* Total trace count */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* Whether metrics consent is active */
    @SerialName(value = "consent_given") @Required val consentGiven: kotlin.Boolean

) {


}
