/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Individual transaction (charge or credit).
 *
 * @param transactionId Unique transaction ID
 * @param type Transaction type: charge or credit
 * @param amountMinor Amount in minor units (negative for charges, positive for credits)
 * @param currency Currency code (USD)
 * @param description Transaction description
 * @param createdAt Transaction timestamp (ISO format)
 * @param balanceAfter Account balance after this transaction
 * @param metadata
 * @param transactionType
 * @param externalTransactionId
 */
@Serializable

data class TransactionItem (

    /* Unique transaction ID */
    @SerialName(value = "transaction_id") @Required val transactionId: kotlin.String,

    /* Transaction type: charge or credit */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* Amount in minor units (negative for charges, positive for credits) */
    @SerialName(value = "amount_minor") @Required val amountMinor: kotlin.Int,

    /* Currency code (USD) */
    @SerialName(value = "currency") @Required val currency: kotlin.String,

    /* Transaction description */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* Transaction timestamp (ISO format) */
    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    /* Account balance after this transaction */
    @SerialName(value = "balance_after") @Required val balanceAfter: kotlin.Int,

    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null,

    @SerialName(value = "transaction_type") val transactionType: kotlin.String? = null,

    @SerialName(value = "external_transaction_id") val externalTransactionId: kotlin.String? = null

) {


}
