/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant

import ai.ciris.api.models.ActionCount

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Public transparency statistics.
 *
 * @param periodStart Start of reporting period
 * @param periodEnd End of reporting period
 * @param totalInteractions Total interactions processed
 * @param actionsTaken Breakdown by action type
 * @param deferralsToHuman Deferrals to human judgment
 * @param deferralsUncertainty Deferrals due to uncertainty
 * @param deferralsEthical Deferrals for ethical review
 * @param harmfulRequestsBlocked Harmful requests rejected
 * @param rateLimitTriggers Rate limit activations
 * @param emergencyShutdowns Emergency shutdown attempts
 * @param uptimePercentage System uptime %
 * @param averageResponseMs Average response time
 * @param activeAgents Number of active agents
 * @param dataRequestsReceived DSAR requests received
 * @param dataRequestsCompleted DSAR requests completed
 */
@Serializable

data class TransparencyStats (

    /* Start of reporting period */
    @SerialName(value = "period_start") @Required val periodStart: kotlinx.datetime.Instant,

    /* End of reporting period */
    @SerialName(value = "period_end") @Required val periodEnd: kotlinx.datetime.Instant,

    /* Total interactions processed */
    @SerialName(value = "total_interactions") @Required val totalInteractions: kotlin.Int,

    /* Breakdown by action type */
    @SerialName(value = "actions_taken") @Required val actionsTaken: kotlin.collections.List<ActionCount>,

    /* Deferrals to human judgment */
    @SerialName(value = "deferrals_to_human") @Required val deferralsToHuman: kotlin.Int,

    /* Deferrals due to uncertainty */
    @SerialName(value = "deferrals_uncertainty") @Required val deferralsUncertainty: kotlin.Int,

    /* Deferrals for ethical review */
    @SerialName(value = "deferrals_ethical") @Required val deferralsEthical: kotlin.Int,

    /* Harmful requests rejected */
    @SerialName(value = "harmful_requests_blocked") @Required val harmfulRequestsBlocked: kotlin.Int,

    /* Rate limit activations */
    @SerialName(value = "rate_limit_triggers") @Required val rateLimitTriggers: kotlin.Int,

    /* Emergency shutdown attempts */
    @SerialName(value = "emergency_shutdowns") @Required val emergencyShutdowns: kotlin.Int,

    /* System uptime % */
    @SerialName(value = "uptime_percentage") @Required val uptimePercentage: kotlin.Double,

    /* Average response time */
    @SerialName(value = "average_response_ms") @Required val averageResponseMs: kotlin.Double,

    /* Number of active agents */
    @SerialName(value = "active_agents") @Required val activeAgents: kotlin.Int,

    /* DSAR requests received */
    @SerialName(value = "data_requests_received") @Required val dataRequestsReceived: kotlin.Int,

    /* DSAR requests completed */
    @SerialName(value = "data_requests_completed") @Required val dataRequestsCompleted: kotlin.Int

) {


}
