/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * WA guidance response.
 *
 * @param guidance Wisdom guidance provided
 * @param waId ID of WA who provided guidance
 * @param confidence Confidence level (0-1)
 * @param timestamp
 * @param additionalContext Additional context
 */
@Serializable

data class WAGuidanceResponse (

    /* Wisdom guidance provided */
    @SerialName(value = "guidance") @Required val guidance: kotlin.String,

    /* ID of WA who provided guidance */
    @SerialName(value = "wa_id") @Required val waId: kotlin.String,

    /* Confidence level (0-1) */
    @SerialName(value = "confidence") @Required val confidence: kotlin.Double,

    @SerialName(value = "timestamp") @Required val timestamp: kotlin.String?,

    /* Additional context */
    @SerialName(value = "additional_context") val additionalContext: kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue>? = null

) {


}
