/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for WA key existence check.
 *
 * @param exists Whether the key file exists
 * @param filename The filename that was checked
 * @param error
 * @param validSize
 * @param propertySize
 */
@Serializable

data class WAKeyCheckResponse (

    /* Whether the key file exists */
    @SerialName(value = "exists") @Required val exists: kotlin.Boolean,

    /* The filename that was checked */
    @SerialName(value = "filename") @Required val filename: kotlin.String,

    @SerialName(value = "error") val error: kotlin.String? = null,

    @SerialName(value = "valid_size") val validSize: kotlin.Boolean? = null,

    @SerialName(value = "size") val propertySize: kotlin.Int? = null

) {


}
