/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import kotlinx.datetime.Instant


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Permission granted to a WA.
 *
 * @param permissionId
 * @param waId
 * @param permissionType
 * @param permissionName
 * @param grantedBy
 * @param grantedAt
 * @param resource
 * @param expiresAt
 * @param metadata
 */
@Serializable

data class WAPermission (

    @SerialName(value = "permission_id") @Required val permissionId: kotlin.String,

    @SerialName(value = "wa_id") @Required val waId: kotlin.String,

    @SerialName(value = "permission_type") @Required val permissionType: kotlin.String,

    @SerialName(value = "permission_name") @Required val permissionName: kotlin.String,

    @SerialName(value = "granted_by") @Required val grantedBy: kotlin.String,

    @SerialName(value = "granted_at") @Required val grantedAt: kotlinx.datetime.Instant,

    @SerialName(value = "resource") val resource: kotlin.String? = null,

    @SerialName(value = "expires_at") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}
