/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ActionCount

class ActionCountTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionCount
        //val modelInstance = ActionCount()

        // to test the property `action` - Action type (SPEAK, DEFER, REJECT, etc.)
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `count` - Number of times action was taken
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `percentage` - Percentage of total actions
        should("test percentage") {
            // uncomment below to test the property
            //modelInstance.percentage shouldBe ("TODO")
        }

    }
}
