/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AdapterActionRequest
import ai.ciris.api.models.AnyOfLessThanGreaterThan

class AdapterActionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AdapterActionRequest
        //val modelInstance = AdapterActionRequest()

        // to test the property `config` - Adapter configuration
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

        // to test the property `force` - Force the operation
        should("test force") {
            // uncomment below to test the property
            //modelInstance.force shouldBe ("TODO")
        }

        // to test the property `persist` - Whether to persist this adapter config for auto-load on restart. When True, the adapter will be automatically restored after agent restart.
        should("test persist") {
            // uncomment below to test the property
            //modelInstance.persist shouldBe ("TODO")
        }

    }
}
