/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AgentIdentity
import ai.ciris.api.models.AgentLineage
import ai.ciris.api.models.ServiceAvailability

class AgentIdentityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgentIdentity
        //val modelInstance = AgentIdentity()

        // to test the property `agentId` - Unique agent identifier
        should("test agentId") {
            // uncomment below to test the property
            //modelInstance.agentId shouldBe ("TODO")
        }

        // to test the property `name` - Agent name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `purpose` - Agent's purpose
        should("test purpose") {
            // uncomment below to test the property
            //modelInstance.purpose shouldBe ("TODO")
        }

        // to test the property `createdAt` - When agent was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `lineage` - Agent lineage information
        should("test lineage") {
            // uncomment below to test the property
            //modelInstance.lineage shouldBe ("TODO")
        }

        // to test the property `varianceThreshold` - Identity variance threshold
        should("test varianceThreshold") {
            // uncomment below to test the property
            //modelInstance.varianceThreshold shouldBe ("TODO")
        }

        // to test the property `tools` - Available tools
        should("test tools") {
            // uncomment below to test the property
            //modelInstance.tools shouldBe ("TODO")
        }

        // to test the property `handlers` - Active handlers
        should("test handlers") {
            // uncomment below to test the property
            //modelInstance.handlers shouldBe ("TODO")
        }

        // to test the property `services` - Service availability
        should("test services") {
            // uncomment below to test the property
            //modelInstance.services shouldBe ("TODO")
        }

        // to test the property `permissions` - Agent permissions
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

    }
}
