/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AgentTemplate

class AgentTemplateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgentTemplate
        //val modelInstance = AgentTemplate()

        // to test the property `id` - Template ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - Display name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - Template description
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `identity` - Agent identity/purpose
        should("test identity") {
            // uncomment below to test the property
            //modelInstance.identity shouldBe ("TODO")
        }

        // to test the property `stewardshipTier` - Book VI Stewardship Tier (1-5, higher = more oversight)
        should("test stewardshipTier") {
            // uncomment below to test the property
            //modelInstance.stewardshipTier shouldBe ("TODO")
        }

        // to test the property `creatorId` - Creator/team identifier who signed this template
        should("test creatorId") {
            // uncomment below to test the property
            //modelInstance.creatorId shouldBe ("TODO")
        }

        // to test the property `signature` - Cryptographic signature verifying template authenticity
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `exampleUseCases` - Example use cases
        should("test exampleUseCases") {
            // uncomment below to test the property
            //modelInstance.exampleUseCases shouldBe ("TODO")
        }

        // to test the property `supportedSops` - Supported Standard Operating Procedures (SOPs) for ticket workflows
        should("test supportedSops") {
            // uncomment below to test the property
            //modelInstance.supportedSops shouldBe ("TODO")
        }

    }
}
