/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.APIResponseThoughtStep

class APIResponseThoughtStepTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of APIResponseThoughtStep
        //val modelInstance = APIResponseThoughtStep()

        // to test the property `step` - Step number
        should("test step") {
            // uncomment below to test the property
            //modelInstance.step shouldBe ("TODO")
        }

        // to test the property `content` - Thought content
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `timestamp` - When thought occurred
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `depth` - Reasoning depth
        should("test depth") {
            // uncomment below to test the property
            //modelInstance.depth shouldBe ("TODO")
        }

        // to test the property `action`
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `confidence`
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

    }
}
