/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AuditEntryResponse
import ai.ciris.api.models.AuditContext

class AuditEntryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditEntryResponse
        //val modelInstance = AuditEntryResponse()

        // to test the property `id` - Audit entry ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `action` - Action performed
        should("test action") {
            // uncomment below to test the property
            //modelInstance.action shouldBe ("TODO")
        }

        // to test the property `actor` - Who performed the action
        should("test actor") {
            // uncomment below to test the property
            //modelInstance.actor shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `context` - Action context
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `signature`
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `hashChain`
        should("test hashChain") {
            // uncomment below to test the property
            //modelInstance.hashChain shouldBe ("TODO")
        }

        // to test the property `storageSources` - Storage locations: graph, jsonl, sqlite
        should("test storageSources") {
            // uncomment below to test the property
            //modelInstance.storageSources shouldBe ("TODO")
        }

    }
}
