/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AuditExportResponse

class AuditExportResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditExportResponse
        //val modelInstance = AuditExportResponse()

        // to test the property `format` - Export format
        should("test format") {
            // uncomment below to test the property
            //modelInstance.format shouldBe ("TODO")
        }

        // to test the property `totalEntries` - Total entries exported
        should("test totalEntries") {
            // uncomment below to test the property
            //modelInstance.totalEntries shouldBe ("TODO")
        }

        // to test the property `exportUrl`
        should("test exportUrl") {
            // uncomment below to test the property
            //modelInstance.exportUrl shouldBe ("TODO")
        }

        // to test the property `exportData`
        should("test exportData") {
            // uncomment below to test the property
            //modelInstance.exportData shouldBe ("TODO")
        }

    }
}
