/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.AuditEntriesResponse
import ai.ciris.api.models.AuditEntryResponse

class AuditEntriesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditEntriesResponse
        //val modelInstance = AuditEntriesResponse()

        // to test the property `propertyEntries` - Audit entries
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

        // to test the property `total` - Total matching entries
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `offset` - Results offset
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `limit` - Results limit
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

    }
}
