/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ChannelContext

class ChannelContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChannelContext
        //val modelInstance = ChannelContext()

        // to test the property `channelId` - Unique channel identifier
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `channelType` - Type of channel (discord, cli, api)
        should("test channelType") {
            // uncomment below to test the property
            //modelInstance.channelType shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `channelName`
        should("test channelName") {
            // uncomment below to test the property
            //modelInstance.channelName shouldBe ("TODO")
        }

        // to test the property `isPrivate` - Whether channel is private
        should("test isPrivate") {
            // uncomment below to test the property
            //modelInstance.isPrivate shouldBe ("TODO")
        }

        // to test the property `participants` - Channel participants
        should("test participants") {
            // uncomment below to test the property
            //modelInstance.participants shouldBe ("TODO")
        }

        // to test the property `isActive` - Whether channel is active
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `lastActivity`
        should("test lastActivity") {
            // uncomment below to test the property
            //modelInstance.lastActivity shouldBe ("TODO")
        }

        // to test the property `messageCount` - Total messages in channel
        should("test messageCount") {
            // uncomment below to test the property
            //modelInstance.messageCount shouldBe ("TODO")
        }

        // to test the property `allowedActions` - Allowed actions in channel
        should("test allowedActions") {
            // uncomment below to test the property
            //modelInstance.allowedActions shouldBe ("TODO")
        }

        // to test the property `moderationLevel` - Moderation level
        should("test moderationLevel") {
            // uncomment below to test the property
            //modelInstance.moderationLevel shouldBe ("TODO")
        }

        // to test the property `memorizedAttributes` - Additional attributes the agent memorized about this channel
        should("test memorizedAttributes") {
            // uncomment below to test the property
            //modelInstance.memorizedAttributes shouldBe ("TODO")
        }

    }
}
