/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConfigItemResponse
import ai.ciris.api.models.ConfigValue

class ConfigItemResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigItemResponse
        //val modelInstance = ConfigItemResponse()

        // to test the property `key` - Configuration key
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property ``value`` - Configuration value (may be redacted)
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `updatedBy` - Who updated this config
        should("test updatedBy") {
            // uncomment below to test the property
            //modelInstance.updatedBy shouldBe ("TODO")
        }

        // to test the property `isSensitive` - Whether value contains sensitive data
        should("test isSensitive") {
            // uncomment below to test the property
            //modelInstance.isSensitive shouldBe ("TODO")
        }

    }
}
