/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConfigurationFieldDefinition
import ai.ciris.api.models.AnyOfLessThanGreaterThan
import ai.ciris.api.models.Max
import ai.ciris.api.models.Min

class ConfigurationFieldDefinitionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigurationFieldDefinition
        //val modelInstance = ConfigurationFieldDefinition()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `fieldId`
        should("test fieldId") {
            // uncomment below to test the property
            //modelInstance.fieldId shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `inputType`
        should("test inputType") {
            // uncomment below to test the property
            //modelInstance.inputType shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `placeholder`
        should("test placeholder") {
            // uncomment below to test the property
            //modelInstance.placeholder shouldBe ("TODO")
        }

        // to test the property `default` - Default value
        should("test default") {
            // uncomment below to test the property
            //modelInstance.default shouldBe ("TODO")
        }

        // to test the property `required` - Whether this field is required
        should("test required") {
            // uncomment below to test the property
            //modelInstance.required shouldBe ("TODO")
        }

        // to test the property `min`
        should("test min") {
            // uncomment below to test the property
            //modelInstance.min shouldBe ("TODO")
        }

        // to test the property `max`
        should("test max") {
            // uncomment below to test the property
            //modelInstance.max shouldBe ("TODO")
        }

        // to test the property `dependsOn`
        should("test dependsOn") {
            // uncomment below to test the property
            //modelInstance.dependsOn shouldBe ("TODO")
        }

    }
}
