/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConfigureOAuthProviderRequest

class ConfigureOAuthProviderRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigureOAuthProviderRequest
        //val modelInstance = ConfigureOAuthProviderRequest()

        // to test the property `provider` - Provider name
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `clientId` - OAuth client ID
        should("test clientId") {
            // uncomment below to test the property
            //modelInstance.clientId shouldBe ("TODO")
        }

        // to test the property `clientSecret` - OAuth client secret
        should("test clientSecret") {
            // uncomment below to test the property
            //modelInstance.clientSecret shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
