/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConsentStatus
import ai.ciris.api.models.ConsentCategory
import ai.ciris.api.models.ConsentStream

class ConsentStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsentStatus
        //val modelInstance = ConsentStatus()

        // to test the property `userId` - User identifier
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `stream` - Current consent stream
        should("test stream") {
            // uncomment below to test the property
            //modelInstance.stream shouldBe ("TODO")
        }

        // to test the property `categories` - What they consented to
        should("test categories") {
            // uncomment below to test the property
            //modelInstance.categories shouldBe ("TODO")
        }

        // to test the property `grantedAt` - When consent was granted
        should("test grantedAt") {
            // uncomment below to test the property
            //modelInstance.grantedAt shouldBe ("TODO")
        }

        // to test the property `lastModified` - Last modification time
        should("test lastModified") {
            // uncomment below to test the property
            //modelInstance.lastModified shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `impactScore` - Contribution to collective learning
        should("test impactScore") {
            // uncomment below to test the property
            //modelInstance.impactScore shouldBe ("TODO")
        }

        // to test the property `attributionCount` - Number of patterns attributed
        should("test attributionCount") {
            // uncomment below to test the property
            //modelInstance.attributionCount shouldBe ("TODO")
        }

    }
}
