/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConsentCleanupResponse

class ConsentCleanupResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsentCleanupResponse
        //val modelInstance = ConsentCleanupResponse()

        // to test the property `cleaned` - Number of records cleaned
        should("test cleaned") {
            // uncomment below to test the property
            //modelInstance.cleaned shouldBe ("TODO")
        }

        // to test the property `message` - Cleanup result message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
