/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConsentDecayStatus

class ConsentDecayStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsentDecayStatus
        //val modelInstance = ConsentDecayStatus()

        // to test the property `userId` - User being forgotten
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `decayStarted` - When decay began
        should("test decayStarted") {
            // uncomment below to test the property
            //modelInstance.decayStarted shouldBe ("TODO")
        }

        // to test the property `identitySevered` - Identity disconnected from patterns
        should("test identitySevered") {
            // uncomment below to test the property
            //modelInstance.identitySevered shouldBe ("TODO")
        }

        // to test the property `patternsAnonymized` - Patterns converted to anonymous
        should("test patternsAnonymized") {
            // uncomment below to test the property
            //modelInstance.patternsAnonymized shouldBe ("TODO")
        }

        // to test the property `decayCompleteAt` - When decay will complete (90 days)
        should("test decayCompleteAt") {
            // uncomment below to test the property
            //modelInstance.decayCompleteAt shouldBe ("TODO")
        }

        // to test the property `safetyPatternsRetained` - Patterns kept for safety
        should("test safetyPatternsRetained") {
            // uncomment below to test the property
            //modelInstance.safetyPatternsRetained shouldBe ("TODO")
        }

    }
}
