/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ConscienceResult
import ai.ciris.api.models.ConscienceResultDetailsValue

class ConscienceResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConscienceResult
        //val modelInstance = ConscienceResult()

        // to test the property `conscienceName` - Name of the conscience
        should("test conscienceName") {
            // uncomment below to test the property
            //modelInstance.conscienceName shouldBe ("TODO")
        }

        // to test the property `passed` - Whether the conscience check passed
        should("test passed") {
            // uncomment below to test the property
            //modelInstance.passed shouldBe ("TODO")
        }

        // to test the property `severity` - Severity level of the result
        should("test severity") {
            // uncomment below to test the property
            //modelInstance.severity shouldBe ("TODO")
        }

        // to test the property `message` - Result message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `overrideAction`
        should("test overrideAction") {
            // uncomment below to test the property
            //modelInstance.overrideAction shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

    }
}
