/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.DeferralListResponse
import ai.ciris.api.models.PendingDeferral

class DeferralListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeferralListResponse
        //val modelInstance = DeferralListResponse()

        // to test the property `deferrals` - List of pending deferrals
        should("test deferrals") {
            // uncomment below to test the property
            //modelInstance.deferrals shouldBe ("TODO")
        }

        // to test the property `total` - Total number of pending deferrals
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
