/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.DeferParams
import ai.ciris.api.models.DeferParamsContextValue

class DeferParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeferParams
        //val modelInstance = DeferParams()

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `channelId`
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `deferUntil`
        should("test deferUntil") {
            // uncomment below to test the property
            //modelInstance.deferUntil shouldBe ("TODO")
        }

    }
}
