/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.DetailedMetric
import ai.ciris.api.models.MetricData
import ai.ciris.api.models.ServiceMetricValue

class DetailedMetricTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DetailedMetric
        //val modelInstance = DetailedMetric()

        // to test the property `name` - Metric name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `currentValue` - Current value
        should("test currentValue") {
            // uncomment below to test the property
            //modelInstance.currentValue shouldBe ("TODO")
        }

        // to test the property `unit`
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

        // to test the property `trend` - Trend: up|down|stable
        should("test trend") {
            // uncomment below to test the property
            //modelInstance.trend shouldBe ("TODO")
        }

        // to test the property `hourlyAverage` - Average over last hour
        should("test hourlyAverage") {
            // uncomment below to test the property
            //modelInstance.hourlyAverage shouldBe ("TODO")
        }

        // to test the property `dailyAverage` - Average over last day
        should("test dailyAverage") {
            // uncomment below to test the property
            //modelInstance.dailyAverage shouldBe ("TODO")
        }

        // to test the property `byService` - Values by service
        should("test byService") {
            // uncomment below to test the property
            //modelInstance.byService shouldBe ("TODO")
        }

        // to test the property `recentData` - Recent data points
        should("test recentData") {
            // uncomment below to test the property
            //modelInstance.recentData shouldBe ("TODO")
        }

    }
}
