/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.DMAContext
import ai.ciris.api.models.DMADecision

class DMAContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DMAContext
        //val modelInstance = DMAContext()

        // to test the property `domainKnowledge` - Domain-specific knowledge from agent identity
        should("test domainKnowledge") {
            // uncomment below to test the property
            //modelInstance.domainKnowledge shouldBe ("TODO")
        }

        // to test the property `similarDecisions` - Similar past decisions for context
        should("test similarDecisions") {
            // uncomment below to test the property
            //modelInstance.similarDecisions shouldBe ("TODO")
        }

        // to test the property `timeConstraints`
        should("test timeConstraints") {
            // uncomment below to test the property
            //modelInstance.timeConstraints shouldBe ("TODO")
        }

        // to test the property `userPreferences` - Known user preferences
        should("test userPreferences") {
            // uncomment below to test the property
            //modelInstance.userPreferences shouldBe ("TODO")
        }

        // to test the property `communityGuidelines` - Applicable community guidelines
        should("test communityGuidelines") {
            // uncomment below to test the property
            //modelInstance.communityGuidelines shouldBe ("TODO")
        }

    }
}
