/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.DSARInitiateResponse

class DSARInitiateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DSARInitiateResponse
        //val modelInstance = DSARInitiateResponse()

        // to test the property `requestId` - DSAR request identifier
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `userId` - User identifier
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `requestType` - Type of DSAR request
        should("test requestType") {
            // uncomment below to test the property
            //modelInstance.requestType shouldBe ("TODO")
        }

        // to test the property `status` - Request status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `exportData` - Exported data
        should("test exportData") {
            // uncomment below to test the property
            //modelInstance.exportData shouldBe ("TODO")
        }

    }
}
