/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.EntryVerification

class EntryVerificationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntryVerification
        //val modelInstance = EntryVerification()

        // to test the property `signatureValid` - Whether signature is valid
        should("test signatureValid") {
            // uncomment below to test the property
            //modelInstance.signatureValid shouldBe ("TODO")
        }

        // to test the property `hashChainValid` - Whether hash chain is intact
        should("test hashChainValid") {
            // uncomment below to test the property
            //modelInstance.hashChainValid shouldBe ("TODO")
        }

        // to test the property `verifiedAt` - When verification occurred
        should("test verifiedAt") {
            // uncomment below to test the property
            //modelInstance.verifiedAt shouldBe ("TODO")
        }

        // to test the property `verifier` - Who performed verification
        should("test verifier") {
            // uncomment below to test the property
            //modelInstance.verifier shouldBe ("TODO")
        }

        // to test the property `algorithm` - Hash algorithm used
        should("test algorithm") {
            // uncomment below to test the property
            //modelInstance.algorithm shouldBe ("TODO")
        }

        // to test the property `previousHashMatch`
        should("test previousHashMatch") {
            // uncomment below to test the property
            //modelInstance.previousHashMatch shouldBe ("TODO")
        }

    }
}
