/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.EthicalDMAResult

class EthicalDMAResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EthicalDMAResult
        //val modelInstance = EthicalDMAResult()

        // to test the property `stakeholders` - Comma-separated list of all stakeholders who could possibly be affected by the agent's action or inaction (e.g., 'user, community, system, third-parties')
        should("test stakeholders") {
            // uncomment below to test the property
            //modelInstance.stakeholders shouldBe ("TODO")
        }

        // to test the property `conflicts` - Comma-separated list of potential conflicts between stakeholder interests (e.g., 'user privacy vs system learning, individual benefit vs community harm'). Use 'none' if no conflicts identified.
        should("test conflicts") {
            // uncomment below to test the property
            //modelInstance.conflicts shouldBe ("TODO")
        }

        // to test the property `reasoning` - Ethical reasoning for the identified stakeholders and conflicts
        should("test reasoning") {
            // uncomment below to test the property
            //modelInstance.reasoning shouldBe ("TODO")
        }

        // to test the property `alignmentCheck` - Detailed ethical analysis addressing each CIRIS principle
        should("test alignmentCheck") {
            // uncomment below to test the property
            //modelInstance.alignmentCheck shouldBe ("TODO")
        }

    }
}
