/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.GooglePlayVerifyResponse

class GooglePlayVerifyResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GooglePlayVerifyResponse
        //val modelInstance = GooglePlayVerifyResponse()

        // to test the property `success` - Whether verification succeeded
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `creditsAdded` - Credits added from this purchase
        should("test creditsAdded") {
            // uncomment below to test the property
            //modelInstance.creditsAdded shouldBe ("TODO")
        }

        // to test the property `newBalance` - New credit balance after purchase
        should("test newBalance") {
            // uncomment below to test the property
            //modelInstance.newBalance shouldBe ("TODO")
        }

        // to test the property `alreadyProcessed` - Whether purchase was already processed
        should("test alreadyProcessed") {
            // uncomment below to test the property
            //modelInstance.alreadyProcessed shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
