/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.InteractResponse

class InteractResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InteractResponse
        //val modelInstance = InteractResponse()

        // to test the property `messageId` - Unique message ID
        should("test messageId") {
            // uncomment below to test the property
            //modelInstance.messageId shouldBe ("TODO")
        }

        // to test the property `response` - Agent's response
        should("test response") {
            // uncomment below to test the property
            //modelInstance.response shouldBe ("TODO")
        }

        // to test the property `state` - Agent's cognitive state after processing
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `processingTimeMs` - Time taken to process
        should("test processingTimeMs") {
            // uncomment below to test the property
            //modelInstance.processingTimeMs shouldBe ("TODO")
        }

    }
}
