/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.LogContext
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

class LogContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogContext
        //val modelInstance = LogContext()

        // to test the property `traceId`
        should("test traceId") {
            // uncomment below to test the property
            //modelInstance.traceId shouldBe ("TODO")
        }

        // to test the property `correlationId`
        should("test correlationId") {
            // uncomment below to test the property
            //modelInstance.correlationId shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `entityId`
        should("test entityId") {
            // uncomment below to test the property
            //modelInstance.entityId shouldBe ("TODO")
        }

        // to test the property `errorDetails`
        should("test errorDetails") {
            // uncomment below to test the property
            //modelInstance.errorDetails shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
