/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.LoginResponse
import ai.ciris.api.models.UserRole

class LoginResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoginResponse
        //val modelInstance = LoginResponse()

        // to test the property `accessToken` - JWT access token
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `expiresIn` - Token lifetime in seconds
        should("test expiresIn") {
            // uncomment below to test the property
            //modelInstance.expiresIn shouldBe ("TODO")
        }

        // to test the property `userId` - Authenticated user ID
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `role` - User's role
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `tokenType` - Token type
        should("test tokenType") {
            // uncomment below to test the property
            //modelInstance.tokenType shouldBe ("TODO")
        }

    }
}
