/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.MetricAggregate

class MetricAggregateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetricAggregate
        //val modelInstance = MetricAggregate()

        // to test the property `min` - Minimum value
        should("test min") {
            // uncomment below to test the property
            //modelInstance.min shouldBe ("TODO")
        }

        // to test the property `max` - Maximum value
        should("test max") {
            // uncomment below to test the property
            //modelInstance.max shouldBe ("TODO")
        }

        // to test the property `avg` - Average value
        should("test avg") {
            // uncomment below to test the property
            //modelInstance.avg shouldBe ("TODO")
        }

        // to test the property `sum` - Sum of values
        should("test sum") {
            // uncomment below to test the property
            //modelInstance.sum shouldBe ("TODO")
        }

        // to test the property `count` - Number of data points
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `p50`
        should("test p50") {
            // uncomment below to test the property
            //modelInstance.p50 shouldBe ("TODO")
        }

        // to test the property `p95`
        should("test p95") {
            // uncomment below to test the property
            //modelInstance.p95 shouldBe ("TODO")
        }

        // to test the property `p99`
        should("test p99") {
            // uncomment below to test the property
            //modelInstance.p99 shouldBe ("TODO")
        }

    }
}
