/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.MintWARequest
import ai.ciris.api.models.WARole

class MintWARequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MintWARequest
        //val modelInstance = MintWARequest()

        // to test the property `waRole` - Role to grant: AUTHORITY or OBSERVER
        should("test waRole") {
            // uncomment below to test the property
            //modelInstance.waRole shouldBe ("TODO")
        }

        // to test the property `signature`
        should("test signature") {
            // uncomment below to test the property
            //modelInstance.signature shouldBe ("TODO")
        }

        // to test the property `privateKeyPath`
        should("test privateKeyPath") {
            // uncomment below to test the property
            //modelInstance.privateKeyPath shouldBe ("TODO")
        }

    }
}
