/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ModuleConfigParameter
import ai.ciris.api.models.Default

class ModuleConfigParameterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ModuleConfigParameter
        //val modelInstance = ModuleConfigParameter()

        // to test the property `name` - Parameter name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `paramType` - Parameter type (string, integer, float, boolean, array)
        should("test paramType") {
            // uncomment below to test the property
            //modelInstance.paramType shouldBe ("TODO")
        }

        // to test the property `description` - Parameter description
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `default`
        should("test default") {
            // uncomment below to test the property
            //modelInstance.default shouldBe ("TODO")
        }

        // to test the property `envVar`
        should("test envVar") {
            // uncomment below to test the property
            //modelInstance.envVar shouldBe ("TODO")
        }

        // to test the property `required` - Whether parameter is required
        should("test required") {
            // uncomment below to test the property
            //modelInstance.required shouldBe ("TODO")
        }

        // to test the property `sensitivity`
        should("test sensitivity") {
            // uncomment below to test the property
            //modelInstance.sensitivity shouldBe ("TODO")
        }

    }
}
