/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ObserveParams
import ai.ciris.api.models.ChannelContext
import ai.ciris.api.models.DeferParamsContextValue

class ObserveParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ObserveParams
        //val modelInstance = ObserveParams()

        // to test the property `channelId`
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `channelContext`
        should("test channelContext") {
            // uncomment below to test the property
            //modelInstance.channelContext shouldBe ("TODO")
        }

        // to test the property `active`
        should("test active") {
            // uncomment below to test the property
            //modelInstance.active shouldBe ("TODO")
        }

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

    }
}
