/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.PartnershipStatusResponse

class PartnershipStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PartnershipStatusResponse
        //val modelInstance = PartnershipStatusResponse()

        // to test the property `currentStream` - Current consent stream
        should("test currentStream") {
            // uncomment below to test the property
            //modelInstance.currentStream shouldBe ("TODO")
        }

        // to test the property `partnershipStatus` - Partnership request status
        should("test partnershipStatus") {
            // uncomment below to test the property
            //modelInstance.partnershipStatus shouldBe ("TODO")
        }

        // to test the property `message` - Status message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
