/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.PermissionRequestUser
import ai.ciris.api.models.UserRole

class PermissionRequestUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PermissionRequestUser
        //val modelInstance = PermissionRequestUser()

        // to test the property `id` - User ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `role` - Current role
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `permissionRequestedAt` - When permissions were requested
        should("test permissionRequestedAt") {
            // uncomment below to test the property
            //modelInstance.permissionRequestedAt shouldBe ("TODO")
        }

        // to test the property `hasSendMessages` - Whether user already has SEND_MESSAGES permission
        should("test hasSendMessages") {
            // uncomment below to test the property
            //modelInstance.hasSendMessages shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `oauthName`
        should("test oauthName") {
            // uncomment below to test the property
            //modelInstance.oauthName shouldBe ("TODO")
        }

        // to test the property `oauthPicture`
        should("test oauthPicture") {
            // uncomment below to test the property
            //modelInstance.oauthPicture shouldBe ("TODO")
        }

    }
}
