/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ProcessorQueueStatus

class ProcessorQueueStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProcessorQueueStatus
        //val modelInstance = ProcessorQueueStatus()

        // to test the property `processorName` - Processor name
        should("test processorName") {
            // uncomment below to test the property
            //modelInstance.processorName shouldBe ("TODO")
        }

        // to test the property `queueSize` - Current queue size
        should("test queueSize") {
            // uncomment below to test the property
            //modelInstance.queueSize shouldBe ("TODO")
        }

        // to test the property `maxSize` - Maximum queue size
        should("test maxSize") {
            // uncomment below to test the property
            //modelInstance.maxSize shouldBe ("TODO")
        }

        // to test the property `processingRate` - Messages per second
        should("test processingRate") {
            // uncomment below to test the property
            //modelInstance.processingRate shouldBe ("TODO")
        }

        // to test the property `averageLatencyMs` - Average processing latency
        should("test averageLatencyMs") {
            // uncomment below to test the property
            //modelInstance.averageLatencyMs shouldBe ("TODO")
        }

        // to test the property `oldestMessageAgeSeconds`
        should("test oldestMessageAgeSeconds") {
            // uncomment below to test the property
            //modelInstance.oldestMessageAgeSeconds shouldBe ("TODO")
        }

    }
}
