/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ProcessorStateInfo

class ProcessorStateInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProcessorStateInfo
        //val modelInstance = ProcessorStateInfo()

        // to test the property `name` - State name (WAKEUP, WORK, DREAM, etc.)
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `isActive` - Whether this state is currently active
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `description` - State description
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `capabilities` - What this state can do
        should("test capabilities") {
            // uncomment below to test the property
            //modelInstance.capabilities shouldBe ("TODO")
        }

    }
}
