/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.PurchaseInitiateRequest

class PurchaseInitiateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PurchaseInitiateRequest
        //val modelInstance = PurchaseInitiateRequest()

        // to test the property `returnUrl`
        should("test returnUrl") {
            // uncomment below to test the property
            //modelInstance.returnUrl shouldBe ("TODO")
        }

    }
}
