/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.QueryRequest
import ai.ciris.api.models.GraphScope
import ai.ciris.api.models.NodeType

class QueryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryRequest
        //val modelInstance = QueryRequest()

        // to test the property `nodeId`
        should("test nodeId") {
            // uncomment below to test the property
            //modelInstance.nodeId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `since`
        should("test since") {
            // uncomment below to test the property
            //modelInstance.since shouldBe ("TODO")
        }

        // to test the property `until`
        should("test until") {
            // uncomment below to test the property
            //modelInstance.until shouldBe ("TODO")
        }

        // to test the property `relatedTo`
        should("test relatedTo") {
            // uncomment below to test the property
            //modelInstance.relatedTo shouldBe ("TODO")
        }

        // to test the property `scope`
        should("test scope") {
            // uncomment below to test the property
            //modelInstance.scope shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `limit` - Maximum results
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `offset` - Pagination offset
        should("test offset") {
            // uncomment below to test the property
            //modelInstance.offset shouldBe ("TODO")
        }

        // to test the property `includeEdges` - Include relationship data
        should("test includeEdges") {
            // uncomment below to test the property
            //modelInstance.includeEdges shouldBe ("TODO")
        }

        // to test the property `depth` - Graph traversal depth for relationships
        should("test depth") {
            // uncomment below to test the property
            //modelInstance.depth shouldBe ("TODO")
        }

    }
}
