/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.QueryResponse
import ai.ciris.api.models.QueryResult

class QueryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryResponse
        //val modelInstance = QueryResponse()

        // to test the property `queryType` - Query type executed
        should("test queryType") {
            // uncomment below to test the property
            //modelInstance.queryType shouldBe ("TODO")
        }

        // to test the property `results` - Query results
        should("test results") {
            // uncomment below to test the property
            //modelInstance.results shouldBe ("TODO")
        }

        // to test the property `total` - Total results found
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `executionTimeMs` - Query execution time
        should("test executionTimeMs") {
            // uncomment below to test the property
            //modelInstance.executionTimeMs shouldBe ("TODO")
        }

    }
}
