/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.RemovePersistedResponse

class RemovePersistedResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RemovePersistedResponse
        //val modelInstance = RemovePersistedResponse()

        // to test the property `success` - Whether the removal succeeded
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `adapterType` - Adapter type that was removed
        should("test adapterType") {
            // uncomment below to test the property
            //modelInstance.adapterType shouldBe ("TODO")
        }

        // to test the property `message` - Status message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
