/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ResourceHealthStatus

class ResourceHealthStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceHealthStatus
        //val modelInstance = ResourceHealthStatus()

        // to test the property `status` - Health status: healthy|warning|critical
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `warnings` - Warning messages
        should("test warnings") {
            // uncomment below to test the property
            //modelInstance.warnings shouldBe ("TODO")
        }

    }
}
