/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ResourceTelemetryResponse
import ai.ciris.api.models.ResourceHealthStatus
import ai.ciris.api.models.ResourceHistoryPoint
import ai.ciris.api.models.ResourceLimits
import ai.ciris.api.models.ResourceUsageData

class ResourceTelemetryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceTelemetryResponse
        //val modelInstance = ResourceTelemetryResponse()

        // to test the property `current` - Current resource usage
        should("test current") {
            // uncomment below to test the property
            //modelInstance.current shouldBe ("TODO")
        }

        // to test the property `limits` - Resource limits
        should("test limits") {
            // uncomment below to test the property
            //modelInstance.limits shouldBe ("TODO")
        }

        // to test the property `health` - Health status
        should("test health") {
            // uncomment below to test the property
            //modelInstance.health shouldBe ("TODO")
        }

        // to test the property `history` - Historical data
        should("test history") {
            // uncomment below to test the property
            //modelInstance.history shouldBe ("TODO")
        }

    }
}
