/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ResourceLimits

class ResourceLimitsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceLimits
        //val modelInstance = ResourceLimits()

        // to test the property `maxMemoryMb` - Maximum memory in MB
        should("test maxMemoryMb") {
            // uncomment below to test the property
            //modelInstance.maxMemoryMb shouldBe ("TODO")
        }

        // to test the property `maxCpuPercent` - Maximum CPU percentage
        should("test maxCpuPercent") {
            // uncomment below to test the property
            //modelInstance.maxCpuPercent shouldBe ("TODO")
        }

        // to test the property `maxDiskBytes` - Maximum disk usage in bytes
        should("test maxDiskBytes") {
            // uncomment below to test the property
            //modelInstance.maxDiskBytes shouldBe ("TODO")
        }

    }
}
