/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ResourceHistoryPoint

class ResourceHistoryPointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceHistoryPoint
        //val modelInstance = ResourceHistoryPoint()

        // to test the property `timestamp` - Timestamp of measurement
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `cpuPercent` - CPU usage percentage
        should("test cpuPercent") {
            // uncomment below to test the property
            //modelInstance.cpuPercent shouldBe ("TODO")
        }

        // to test the property `memoryMb` - Memory usage in MB
        should("test memoryMb") {
            // uncomment below to test the property
            //modelInstance.memoryMb shouldBe ("TODO")
        }

    }
}
