/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.RuntimeAdapterStatus
import ai.ciris.api.models.AdapterMetrics
import ai.ciris.api.models.CirisEngineSchemasRuntimeAdapterManagementAdapterConfig
import ai.ciris.api.models.ToolInfo

class RuntimeAdapterStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RuntimeAdapterStatus
        //val modelInstance = RuntimeAdapterStatus()

        // to test the property `adapterId` - Unique Adapter ID
        should("test adapterId") {
            // uncomment below to test the property
            //modelInstance.adapterId shouldBe ("TODO")
        }

        // to test the property `adapterType` - Type of adapter
        should("test adapterType") {
            // uncomment below to test the property
            //modelInstance.adapterType shouldBe ("TODO")
        }

        // to test the property `isRunning` - Whether adapter is running
        should("test isRunning") {
            // uncomment below to test the property
            //modelInstance.isRunning shouldBe ("TODO")
        }

        // to test the property `loadedAt`
        should("test loadedAt") {
            // uncomment below to test the property
            //modelInstance.loadedAt shouldBe ("TODO")
        }

        // to test the property `servicesRegistered` - Services registered by adapter
        should("test servicesRegistered") {
            // uncomment below to test the property
            //modelInstance.servicesRegistered shouldBe ("TODO")
        }

        // to test the property `configParams`
        should("test configParams") {
            // uncomment below to test the property
            //modelInstance.configParams shouldBe ("TODO")
        }

        // to test the property `metrics`
        should("test metrics") {
            // uncomment below to test the property
            //modelInstance.metrics shouldBe ("TODO")
        }

        // to test the property `lastActivity`
        should("test lastActivity") {
            // uncomment below to test the property
            //modelInstance.lastActivity shouldBe ("TODO")
        }

        // to test the property `tools`
        should("test tools") {
            // uncomment below to test the property
            //modelInstance.tools shouldBe ("TODO")
        }

    }
}
