/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ServiceStatus
import ai.ciris.api.models.ServiceMetrics

class ServiceStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceStatus
        //val modelInstance = ServiceStatus()

        // to test the property `name` - Service name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - Service type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `healthy` - Whether service is healthy
        should("test healthy") {
            // uncomment below to test the property
            //modelInstance.healthy shouldBe ("TODO")
        }

        // to test the property `available` - Whether service is available
        should("test available") {
            // uncomment below to test the property
            //modelInstance.available shouldBe ("TODO")
        }

        // to test the property `uptimeSeconds`
        should("test uptimeSeconds") {
            // uncomment below to test the property
            //modelInstance.uptimeSeconds shouldBe ("TODO")
        }

        // to test the property `metrics` - Service-specific metrics
        should("test metrics") {
            // uncomment below to test the property
            //modelInstance.metrics shouldBe ("TODO")
        }

    }
}
