/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ServicesStatusResponse
import ai.ciris.api.models.ServiceStatus

class ServicesStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServicesStatusResponse
        //val modelInstance = ServicesStatusResponse()

        // to test the property `services` - List of service statuses
        should("test services") {
            // uncomment below to test the property
            //modelInstance.services shouldBe ("TODO")
        }

        // to test the property `totalServices` - Total number of services
        should("test totalServices") {
            // uncomment below to test the property
            //modelInstance.totalServices shouldBe ("TODO")
        }

        // to test the property `healthyServices` - Number of healthy services
        should("test healthyServices") {
            // uncomment below to test the property
            //modelInstance.healthyServices shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
