/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ServicePriorityUpdateRequest

class ServicePriorityUpdateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServicePriorityUpdateRequest
        //val modelInstance = ServicePriorityUpdateRequest()

        // to test the property `priority` - New priority level (CRITICAL, HIGH, NORMAL, LOW, FALLBACK)
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `priorityGroup`
        should("test priorityGroup") {
            // uncomment below to test the property
            //modelInstance.priorityGroup shouldBe ("TODO")
        }

        // to test the property `strategy`
        should("test strategy") {
            // uncomment below to test the property
            //modelInstance.strategy shouldBe ("TODO")
        }

    }
}
