/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.SetupConfigResponse

class SetupConfigResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetupConfigResponse
        //val modelInstance = SetupConfigResponse()

        // to test the property `llmProvider`
        should("test llmProvider") {
            // uncomment below to test the property
            //modelInstance.llmProvider shouldBe ("TODO")
        }

        // to test the property `llmBaseUrl`
        should("test llmBaseUrl") {
            // uncomment below to test the property
            //modelInstance.llmBaseUrl shouldBe ("TODO")
        }

        // to test the property `llmModel`
        should("test llmModel") {
            // uncomment below to test the property
            //modelInstance.llmModel shouldBe ("TODO")
        }

        // to test the property `llmApiKeySet` - Whether API key is configured
        should("test llmApiKeySet") {
            // uncomment below to test the property
            //modelInstance.llmApiKeySet shouldBe ("TODO")
        }

        // to test the property `backupLlmBaseUrl`
        should("test backupLlmBaseUrl") {
            // uncomment below to test the property
            //modelInstance.backupLlmBaseUrl shouldBe ("TODO")
        }

        // to test the property `backupLlmModel`
        should("test backupLlmModel") {
            // uncomment below to test the property
            //modelInstance.backupLlmModel shouldBe ("TODO")
        }

        // to test the property `backupLlmApiKeySet` - Whether backup API key is configured
        should("test backupLlmApiKeySet") {
            // uncomment below to test the property
            //modelInstance.backupLlmApiKeySet shouldBe ("TODO")
        }

        // to test the property `templateId`
        should("test templateId") {
            // uncomment below to test the property
            //modelInstance.templateId shouldBe ("TODO")
        }

        // to test the property `enabledAdapters` - Currently enabled adapters
        should("test enabledAdapters") {
            // uncomment below to test the property
            //modelInstance.enabledAdapters shouldBe ("TODO")
        }

        // to test the property `agentPort` - Current agent port
        should("test agentPort") {
            // uncomment below to test the property
            //modelInstance.agentPort shouldBe ("TODO")
        }

    }
}
