/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.SetupCompleteRequest

class SetupCompleteRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetupCompleteRequest
        //val modelInstance = SetupCompleteRequest()

        // to test the property `llmProvider` - LLM provider ID
        should("test llmProvider") {
            // uncomment below to test the property
            //modelInstance.llmProvider shouldBe ("TODO")
        }

        // to test the property `llmApiKey` - LLM API key
        should("test llmApiKey") {
            // uncomment below to test the property
            //modelInstance.llmApiKey shouldBe ("TODO")
        }

        // to test the property `llmBaseUrl`
        should("test llmBaseUrl") {
            // uncomment below to test the property
            //modelInstance.llmBaseUrl shouldBe ("TODO")
        }

        // to test the property `llmModel`
        should("test llmModel") {
            // uncomment below to test the property
            //modelInstance.llmModel shouldBe ("TODO")
        }

        // to test the property `backupLlmApiKey`
        should("test backupLlmApiKey") {
            // uncomment below to test the property
            //modelInstance.backupLlmApiKey shouldBe ("TODO")
        }

        // to test the property `backupLlmBaseUrl`
        should("test backupLlmBaseUrl") {
            // uncomment below to test the property
            //modelInstance.backupLlmBaseUrl shouldBe ("TODO")
        }

        // to test the property `backupLlmModel`
        should("test backupLlmModel") {
            // uncomment below to test the property
            //modelInstance.backupLlmModel shouldBe ("TODO")
        }

        // to test the property `templateId` - Agent template ID
        should("test templateId") {
            // uncomment below to test the property
            //modelInstance.templateId shouldBe ("TODO")
        }

        // to test the property `enabledAdapters` - List of enabled adapters
        should("test enabledAdapters") {
            // uncomment below to test the property
            //modelInstance.enabledAdapters shouldBe ("TODO")
        }

        // to test the property `adapterConfig` - Adapter-specific configuration
        should("test adapterConfig") {
            // uncomment below to test the property
            //modelInstance.adapterConfig shouldBe ("TODO")
        }

        // to test the property `adminUsername` - New user's username
        should("test adminUsername") {
            // uncomment below to test the property
            //modelInstance.adminUsername shouldBe ("TODO")
        }

        // to test the property `adminPassword`
        should("test adminPassword") {
            // uncomment below to test the property
            //modelInstance.adminPassword shouldBe ("TODO")
        }

        // to test the property `systemAdminPassword`
        should("test systemAdminPassword") {
            // uncomment below to test the property
            //modelInstance.systemAdminPassword shouldBe ("TODO")
        }

        // to test the property `oauthProvider`
        should("test oauthProvider") {
            // uncomment below to test the property
            //modelInstance.oauthProvider shouldBe ("TODO")
        }

        // to test the property `oauthExternalId`
        should("test oauthExternalId") {
            // uncomment below to test the property
            //modelInstance.oauthExternalId shouldBe ("TODO")
        }

        // to test the property `oauthEmail`
        should("test oauthEmail") {
            // uncomment below to test the property
            //modelInstance.oauthEmail shouldBe ("TODO")
        }

        // to test the property `agentPort` - Agent API port
        should("test agentPort") {
            // uncomment below to test the property
            //modelInstance.agentPort shouldBe ("TODO")
        }

    }
}
