/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.StateTransitionResponse

class StateTransitionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StateTransitionResponse
        //val modelInstance = StateTransitionResponse()

        // to test the property `success` - Whether transition was initiated
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `message` - Human-readable status message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

        // to test the property `currentState` - Current cognitive state after transition attempt
        should("test currentState") {
            // uncomment below to test the property
            //modelInstance.currentState shouldBe ("TODO")
        }

        // to test the property `previousState`
        should("test previousState") {
            // uncomment below to test the property
            //modelInstance.previousState shouldBe ("TODO")
        }

    }
}
