/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.StepExecutionResponse

class StepExecutionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StepExecutionResponse
        //val modelInstance = StepExecutionResponse()

        // to test the property `stepId` - ID of the executed step
        should("test stepId") {
            // uncomment below to test the property
            //modelInstance.stepId shouldBe ("TODO")
        }

        // to test the property `success` - Whether step execution succeeded
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property ``data`` - Data returned by the step
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `nextStepIndex`
        should("test nextStepIndex") {
            // uncomment below to test the property
            //modelInstance.nextStepIndex shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `awaitingCallback` - Whether step is waiting for external callback
        should("test awaitingCallback") {
            // uncomment below to test the property
            //modelInstance.awaitingCallback shouldBe ("TODO")
        }

    }
}
