/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.SuccessResponseServicePriorityUpdateResponse
import ai.ciris.api.models.ResponseMetadata
import ai.ciris.api.models.ServicePriorityUpdateResponse

class SuccessResponseServicePriorityUpdateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuccessResponseServicePriorityUpdateResponse
        //val modelInstance = SuccessResponseServicePriorityUpdateResponse()

        // to test the property ``data`` - Response data
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
