/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.SystemOverview

class SystemOverviewTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemOverview
        //val modelInstance = SystemOverview()

        // to test the property `uptimeSeconds` - System uptime
        should("test uptimeSeconds") {
            // uncomment below to test the property
            //modelInstance.uptimeSeconds shouldBe ("TODO")
        }

        // to test the property `cognitiveState` - Current cognitive state
        should("test cognitiveState") {
            // uncomment below to test the property
            //modelInstance.cognitiveState shouldBe ("TODO")
        }

        // to test the property `messagesProcessed24h` - Messages in last 24 hours
        should("test messagesProcessed24h") {
            // uncomment below to test the property
            //modelInstance.messagesProcessed24h shouldBe ("TODO")
        }

        // to test the property `thoughtsProcessed24h` - Thoughts in last 24 hours
        should("test thoughtsProcessed24h") {
            // uncomment below to test the property
            //modelInstance.thoughtsProcessed24h shouldBe ("TODO")
        }

        // to test the property `tasksCompleted24h` - Tasks completed in last 24 hours
        should("test tasksCompleted24h") {
            // uncomment below to test the property
            //modelInstance.tasksCompleted24h shouldBe ("TODO")
        }

        // to test the property `errors24h` - Errors in last 24 hours
        should("test errors24h") {
            // uncomment below to test the property
            //modelInstance.errors24h shouldBe ("TODO")
        }

        // to test the property `tokensLastHour` - Total tokens in last hour
        should("test tokensLastHour") {
            // uncomment below to test the property
            //modelInstance.tokensLastHour shouldBe ("TODO")
        }

        // to test the property `costLastHourCents` - Total cost in last hour (cents)
        should("test costLastHourCents") {
            // uncomment below to test the property
            //modelInstance.costLastHourCents shouldBe ("TODO")
        }

        // to test the property `carbonLastHourGrams` - Total carbon in last hour (grams)
        should("test carbonLastHourGrams") {
            // uncomment below to test the property
            //modelInstance.carbonLastHourGrams shouldBe ("TODO")
        }

        // to test the property `energyLastHourKwh` - Total energy in last hour (kWh)
        should("test energyLastHourKwh") {
            // uncomment below to test the property
            //modelInstance.energyLastHourKwh shouldBe ("TODO")
        }

        // to test the property `tokens24h` - Total tokens in last 24 hours
        should("test tokens24h") {
            // uncomment below to test the property
            //modelInstance.tokens24h shouldBe ("TODO")
        }

        // to test the property `cost24hCents` - Total cost in last 24 hours (cents)
        should("test cost24hCents") {
            // uncomment below to test the property
            //modelInstance.cost24hCents shouldBe ("TODO")
        }

        // to test the property `carbon24hGrams` - Total carbon in last 24 hours (grams)
        should("test carbon24hGrams") {
            // uncomment below to test the property
            //modelInstance.carbon24hGrams shouldBe ("TODO")
        }

        // to test the property `energy24hKwh` - Total energy in last 24 hours (kWh)
        should("test energy24hKwh") {
            // uncomment below to test the property
            //modelInstance.energy24hKwh shouldBe ("TODO")
        }

        // to test the property `memoryMb` - Current memory usage
        should("test memoryMb") {
            // uncomment below to test the property
            //modelInstance.memoryMb shouldBe ("TODO")
        }

        // to test the property `cpuPercent` - Current CPU usage
        should("test cpuPercent") {
            // uncomment below to test the property
            //modelInstance.cpuPercent shouldBe ("TODO")
        }

        // to test the property `healthyServices` - Number of healthy services
        should("test healthyServices") {
            // uncomment below to test the property
            //modelInstance.healthyServices shouldBe ("TODO")
        }

        // to test the property `degradedServices` - Number of degraded services
        should("test degradedServices") {
            // uncomment below to test the property
            //modelInstance.degradedServices shouldBe ("TODO")
        }

        // to test the property `errorRatePercent` - System error rate
        should("test errorRatePercent") {
            // uncomment below to test the property
            //modelInstance.errorRatePercent shouldBe ("TODO")
        }

        // to test the property `currentTask`
        should("test currentTask") {
            // uncomment below to test the property
            //modelInstance.currentTask shouldBe ("TODO")
        }

        // to test the property `reasoningDepth` - Current reasoning depth
        should("test reasoningDepth") {
            // uncomment below to test the property
            //modelInstance.reasoningDepth shouldBe ("TODO")
        }

        // to test the property `activeDeferrals` - Pending WA deferrals
        should("test activeDeferrals") {
            // uncomment below to test the property
            //modelInstance.activeDeferrals shouldBe ("TODO")
        }

        // to test the property `recentIncidents` - Incidents in last hour
        should("test recentIncidents") {
            // uncomment below to test the property
            //modelInstance.recentIncidents shouldBe ("TODO")
        }

        // to test the property `totalMetrics` - Total metrics collected
        should("test totalMetrics") {
            // uncomment below to test the property
            //modelInstance.totalMetrics shouldBe ("TODO")
        }

        // to test the property `activeServices` - Number of active services reporting telemetry
        should("test activeServices") {
            // uncomment below to test the property
            //modelInstance.activeServices shouldBe ("TODO")
        }

        // to test the property `metricsPerSecond` - Current metric ingestion rate
        should("test metricsPerSecond") {
            // uncomment below to test the property
            //modelInstance.metricsPerSecond shouldBe ("TODO")
        }

        // to test the property `cacheHitRate` - Telemetry cache hit rate
        should("test cacheHitRate") {
            // uncomment below to test the property
            //modelInstance.cacheHitRate shouldBe ("TODO")
        }

    }
}
