/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.SystemTimeResponse
import ai.ciris.api.models.TimeSyncStatus

class SystemTimeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemTimeResponse
        //val modelInstance = SystemTimeResponse()

        // to test the property `systemTime`
        should("test systemTime") {
            // uncomment below to test the property
            //modelInstance.systemTime shouldBe ("TODO")
        }

        // to test the property `agentTime`
        should("test agentTime") {
            // uncomment below to test the property
            //modelInstance.agentTime shouldBe ("TODO")
        }

        // to test the property `uptimeSeconds` - Service uptime in seconds
        should("test uptimeSeconds") {
            // uncomment below to test the property
            //modelInstance.uptimeSeconds shouldBe ("TODO")
        }

        // to test the property `timeSync` - Time synchronization status
        should("test timeSync") {
            // uncomment below to test the property
            //modelInstance.timeSync shouldBe ("TODO")
        }

    }
}
