/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.TaskCompleteParams
import ai.ciris.api.models.DeferParamsContextValue

class TaskCompleteParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskCompleteParams
        //val modelInstance = TaskCompleteParams()

        // to test the property `channelId`
        should("test channelId") {
            // uncomment below to test the property
            //modelInstance.channelId shouldBe ("TODO")
        }

        // to test the property `completionReason`
        should("test completionReason") {
            // uncomment below to test the property
            //modelInstance.completionReason shouldBe ("TODO")
        }

        // to test the property `context`
        should("test context") {
            // uncomment below to test the property
            //modelInstance.context shouldBe ("TODO")
        }

        // to test the property `positiveMoment`
        should("test positiveMoment") {
            // uncomment below to test the property
            //modelInstance.positiveMoment shouldBe ("TODO")
        }

        // to test the property `persistImages` - If True, preserve task images after completion. Default False purges images for privacy/storage.
        should("test persistImages") {
            // uncomment below to test the property
            //modelInstance.persistImages shouldBe ("TODO")
        }

    }
}
