/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.TelemetryNodeAttributes

class TelemetryNodeAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetryNodeAttributes
        //val modelInstance = TelemetryNodeAttributes()

        // to test the property `createdBy` - Service or user that created this node
        should("test createdBy") {
            // uncomment below to test the property
            //modelInstance.createdBy shouldBe ("TODO")
        }

        // to test the property `metricName` - Name of the metric
        should("test metricName") {
            // uncomment below to test the property
            //modelInstance.metricName shouldBe ("TODO")
        }

        // to test the property `metricType` - Type: counter, gauge, histogram, summary
        should("test metricType") {
            // uncomment below to test the property
            //modelInstance.metricType shouldBe ("TODO")
        }

        // to test the property ``value`` - Numeric value of the metric
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `startTime` - Start of measurement period
        should("test startTime") {
            // uncomment below to test the property
            //modelInstance.startTime shouldBe ("TODO")
        }

        // to test the property `endTime` - End of measurement period
        should("test endTime") {
            // uncomment below to test the property
            //modelInstance.endTime shouldBe ("TODO")
        }

        // to test the property `durationSeconds` - Duration of measurement period
        should("test durationSeconds") {
            // uncomment below to test the property
            //modelInstance.durationSeconds shouldBe ("TODO")
        }

        // to test the property `serviceName` - Service that generated this metric
        should("test serviceName") {
            // uncomment below to test the property
            //modelInstance.serviceName shouldBe ("TODO")
        }

        // to test the property `createdAt` - When this node was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When this node was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `updatedBy`
        should("test updatedBy") {
            // uncomment below to test the property
            //modelInstance.updatedBy shouldBe ("TODO")
        }

        // to test the property `tags` - Tags for categorization and search
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `version` - Schema version for migration support
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `secretRefs` - Secret reference UUIDs for encrypted data
        should("test secretRefs") {
            // uncomment below to test the property
            //modelInstance.secretRefs shouldBe ("TODO")
        }

        // to test the property `unit`
        should("test unit") {
            // uncomment below to test the property
            //modelInstance.unit shouldBe ("TODO")
        }

        // to test the property `aggregationType`
        should("test aggregationType") {
            // uncomment below to test the property
            //modelInstance.aggregationType shouldBe ("TODO")
        }

        // to test the property `sampleCount` - Number of samples in this metric
        should("test sampleCount") {
            // uncomment below to test the property
            //modelInstance.sampleCount shouldBe ("TODO")
        }

        // to test the property `minValue`
        should("test minValue") {
            // uncomment below to test the property
            //modelInstance.minValue shouldBe ("TODO")
        }

        // to test the property `maxValue`
        should("test maxValue") {
            // uncomment below to test the property
            //modelInstance.maxValue shouldBe ("TODO")
        }

        // to test the property `meanValue`
        should("test meanValue") {
            // uncomment below to test the property
            //modelInstance.meanValue shouldBe ("TODO")
        }

        // to test the property `stdDeviation`
        should("test stdDeviation") {
            // uncomment below to test the property
            //modelInstance.stdDeviation shouldBe ("TODO")
        }

        // to test the property `percentiles` - Percentile values (e.g., p50, p95, p99)
        should("test percentiles") {
            // uncomment below to test the property
            //modelInstance.percentiles shouldBe ("TODO")
        }

        // to test the property `labels` - Metric labels for filtering and grouping
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `host`
        should("test host") {
            // uncomment below to test the property
            //modelInstance.host shouldBe ("TODO")
        }

        // to test the property `warningThreshold`
        should("test warningThreshold") {
            // uncomment below to test the property
            //modelInstance.warningThreshold shouldBe ("TODO")
        }

        // to test the property `criticalThreshold`
        should("test criticalThreshold") {
            // uncomment below to test the property
            //modelInstance.criticalThreshold shouldBe ("TODO")
        }

        // to test the property `thresholdDirection`
        should("test thresholdDirection") {
            // uncomment below to test the property
            //modelInstance.thresholdDirection shouldBe ("TODO")
        }

        // to test the property `resourceType`
        should("test resourceType") {
            // uncomment below to test the property
            //modelInstance.resourceType shouldBe ("TODO")
        }

        // to test the property `resourceLimit`
        should("test resourceLimit") {
            // uncomment below to test the property
            //modelInstance.resourceLimit shouldBe ("TODO")
        }

    }
}
