/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.TimeSyncStatus

class TimeSyncStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeSyncStatus
        //val modelInstance = TimeSyncStatus()

        // to test the property `synchronized` - Whether time is synchronized
        should("test synchronized") {
            // uncomment below to test the property
            //modelInstance.synchronized shouldBe ("TODO")
        }

        // to test the property `driftMs` - Time drift in milliseconds
        should("test driftMs") {
            // uncomment below to test the property
            //modelInstance.driftMs shouldBe ("TODO")
        }

        // to test the property `lastSync`
        should("test lastSync") {
            // uncomment below to test the property
            //modelInstance.lastSync shouldBe ("TODO")
        }

        // to test the property `syncSource` - Sync source (system/mock/ntp)
        should("test syncSource") {
            // uncomment below to test the property
            //modelInstance.syncSource shouldBe ("TODO")
        }

    }
}
