/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ToolPurchaseResponse

class ToolPurchaseResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ToolPurchaseResponse
        //val modelInstance = ToolPurchaseResponse()

        // to test the property `success` - Whether purchase was verified and processed
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `productType` - Tool product type
        should("test productType") {
            // uncomment below to test the property
            //modelInstance.productType shouldBe ("TODO")
        }

        // to test the property `creditsAdded` - Number of credits added
        should("test creditsAdded") {
            // uncomment below to test the property
            //modelInstance.creditsAdded shouldBe ("TODO")
        }

        // to test the property `newBalance` - New total available credits
        should("test newBalance") {
            // uncomment below to test the property
            //modelInstance.newBalance shouldBe ("TODO")
        }

        // to test the property `message` - Status message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
