/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.ToolInfo
import ai.ciris.api.models.PlatformRequirement
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue
import ai.ciris.api.models.ToolParameterSchema

class ToolInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ToolInfo
        //val modelInstance = ToolInfo()

        // to test the property `name` - Tool name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `description` - What the tool does
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `parameters` - Tool parameters schema
        should("test parameters") {
            // uncomment below to test the property
            //modelInstance.parameters shouldBe ("TODO")
        }

        // to test the property `category` - Tool category
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `cost` - Cost to execute the tool
        should("test cost") {
            // uncomment below to test the property
            //modelInstance.cost shouldBe ("TODO")
        }

        // to test the property `whenToUse`
        should("test whenToUse") {
            // uncomment below to test the property
            //modelInstance.whenToUse shouldBe ("TODO")
        }

        // to test the property `contextEnrichment` - If True, tool is automatically run during context gathering to enrich ASPDMA prompt
        should("test contextEnrichment") {
            // uncomment below to test the property
            //modelInstance.contextEnrichment shouldBe ("TODO")
        }

        // to test the property `contextEnrichmentParams`
        should("test contextEnrichmentParams") {
            // uncomment below to test the property
            //modelInstance.contextEnrichmentParams shouldBe ("TODO")
        }

        // to test the property `platformRequirements` - Platform security requirements (e.g., ANDROID_PLAY_INTEGRITY, DPOP)
        should("test platformRequirements") {
            // uncomment below to test the property
            //modelInstance.platformRequirements shouldBe ("TODO")
        }

        // to test the property `platformRequirementsRationale`
        should("test platformRequirementsRationale") {
            // uncomment below to test the property
            //modelInstance.platformRequirementsRationale shouldBe ("TODO")
        }

    }
}
