/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.TracesListResponse
import ai.ciris.api.models.CompleteTraceResponse

class TracesListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TracesListResponse
        //val modelInstance = TracesListResponse()

        // to test the property `traces` - Captured traces
        should("test traces") {
            // uncomment below to test the property
            //modelInstance.traces shouldBe ("TODO")
        }

        // to test the property `total` - Total trace count
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `consentGiven` - Whether metrics consent is active
        should("test consentGiven") {
            // uncomment below to test the property
            //modelInstance.consentGiven shouldBe ("TODO")
        }

    }
}
