/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.UpdatePermissionsRequest

class UpdatePermissionsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdatePermissionsRequest
        //val modelInstance = UpdatePermissionsRequest()

        // to test the property `permissions` - List of permission strings to grant
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

    }
}
