/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.VerificationReport

class VerificationReportTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VerificationReport
        //val modelInstance = VerificationReport()

        // to test the property `verified` - Whether integrity check passed
        should("test verified") {
            // uncomment below to test the property
            //modelInstance.verified shouldBe ("TODO")
        }

        // to test the property `totalEntries` - Total audit entries checked
        should("test totalEntries") {
            // uncomment below to test the property
            //modelInstance.totalEntries shouldBe ("TODO")
        }

        // to test the property `validEntries` - Entries with valid signatures
        should("test validEntries") {
            // uncomment below to test the property
            //modelInstance.validEntries shouldBe ("TODO")
        }

        // to test the property `invalidEntries` - Entries with invalid signatures
        should("test invalidEntries") {
            // uncomment below to test the property
            //modelInstance.invalidEntries shouldBe ("TODO")
        }

        // to test the property `chainIntact` - Whether hash chain is intact
        should("test chainIntact") {
            // uncomment below to test the property
            //modelInstance.chainIntact shouldBe ("TODO")
        }

        // to test the property `verificationStarted` - Verification start time
        should("test verificationStarted") {
            // uncomment below to test the property
            //modelInstance.verificationStarted shouldBe ("TODO")
        }

        // to test the property `verificationCompleted` - Verification end time
        should("test verificationCompleted") {
            // uncomment below to test the property
            //modelInstance.verificationCompleted shouldBe ("TODO")
        }

        // to test the property `durationMs` - Verification duration in milliseconds
        should("test durationMs") {
            // uncomment below to test the property
            //modelInstance.durationMs shouldBe ("TODO")
        }

        // to test the property `missingEntries` - Entries missing from chain
        should("test missingEntries") {
            // uncomment below to test the property
            //modelInstance.missingEntries shouldBe ("TODO")
        }

        // to test the property `lastValidEntry`
        should("test lastValidEntry") {
            // uncomment below to test the property
            //modelInstance.lastValidEntry shouldBe ("TODO")
        }

        // to test the property `firstInvalidEntry`
        should("test firstInvalidEntry") {
            // uncomment below to test the property
            //modelInstance.firstInvalidEntry shouldBe ("TODO")
        }

        // to test the property `errors` - Errors encountered
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property `warnings` - Warnings encountered
        should("test warnings") {
            // uncomment below to test the property
            //modelInstance.warnings shouldBe ("TODO")
        }

    }
}
