/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.WAGuidanceResponse
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue

class WAGuidanceResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WAGuidanceResponse
        //val modelInstance = WAGuidanceResponse()

        // to test the property `guidance` - Wisdom guidance provided
        should("test guidance") {
            // uncomment below to test the property
            //modelInstance.guidance shouldBe ("TODO")
        }

        // to test the property `waId` - ID of WA who provided guidance
        should("test waId") {
            // uncomment below to test the property
            //modelInstance.waId shouldBe ("TODO")
        }

        // to test the property `confidence` - Confidence level (0-1)
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

        // to test the property `timestamp`
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `additionalContext` - Additional context
        should("test additionalContext") {
            // uncomment below to test the property
            //modelInstance.additionalContext shouldBe ("TODO")
        }

    }
}
