/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.models.WAPermission

class WAPermissionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WAPermission
        //val modelInstance = WAPermission()

        // to test the property `permissionId`
        should("test permissionId") {
            // uncomment below to test the property
            //modelInstance.permissionId shouldBe ("TODO")
        }

        // to test the property `waId`
        should("test waId") {
            // uncomment below to test the property
            //modelInstance.waId shouldBe ("TODO")
        }

        // to test the property `permissionType`
        should("test permissionType") {
            // uncomment below to test the property
            //modelInstance.permissionType shouldBe ("TODO")
        }

        // to test the property `permissionName`
        should("test permissionName") {
            // uncomment below to test the property
            //modelInstance.permissionName shouldBe ("TODO")
        }

        // to test the property `grantedBy`
        should("test grantedBy") {
            // uncomment below to test the property
            //modelInstance.grantedBy shouldBe ("TODO")
        }

        // to test the property `grantedAt`
        should("test grantedAt") {
            // uncomment below to test the property
            //modelInstance.grantedAt shouldBe ("TODO")
        }

        // to test the property `resource`
        should("test resource") {
            // uncomment below to test the property
            //modelInstance.resource shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
