/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.AuditApi
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.SuccessResponseAuditEntriesResponse
import ai.ciris.api.models.SuccessResponseAuditEntryDetailResponse
import ai.ciris.api.models.SuccessResponseAuditExportResponse
import ai.ciris.api.models.SuccessResponseVerificationReport

class AuditApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuditApi
        //val apiInstance = AuditApi()

        // to test exportAuditDataV1AuditExportPost
        should("test exportAuditDataV1AuditExportPost") {
            // uncomment below to test exportAuditDataV1AuditExportPost
            //val startDate : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Export start date
            //val endDate : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Export end date
            //val format : kotlin.String = format_example // kotlin.String | Export format
            //val includeVerification : kotlin.Boolean = true // kotlin.Boolean | Include verification data in export
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseAuditExportResponse = apiInstance.exportAuditDataV1AuditExportPost(startDate, endDate, format, includeVerification, authorization)
            //result shouldBe ("TODO")
        }

        // to test getAuditEntryV1AuditEntriesEntryIdGet
        should("test getAuditEntryV1AuditEntriesEntryIdGet") {
            // uncomment below to test getAuditEntryV1AuditEntriesEntryIdGet
            //val entryId : kotlin.String = entryId_example // kotlin.String | Audit entry ID
            //val verify : kotlin.Boolean = true // kotlin.Boolean | Include verification information
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseAuditEntryDetailResponse = apiInstance.getAuditEntryV1AuditEntriesEntryIdGet(entryId, verify, authorization)
            //result shouldBe ("TODO")
        }

        // to test queryAuditEntriesV1AuditEntriesGet
        should("test queryAuditEntriesV1AuditEntriesGet") {
            // uncomment below to test queryAuditEntriesV1AuditEntriesGet
            //val startTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Start of time range
            //val endTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | End of time range
            //val actor : kotlin.String = actor_example // kotlin.String | Filter by actor
            //val eventType : kotlin.String = eventType_example // kotlin.String | Filter by event type
            //val entityId : kotlin.String = entityId_example // kotlin.String | Filter by entity ID
            //val search : kotlin.String = search_example // kotlin.String | Search in audit details
            //val severity : kotlin.String = severity_example // kotlin.String | Filter by severity (info, warning, error)
            //val outcome : kotlin.String = outcome_example // kotlin.String | Filter by outcome (success, failure)
            //val limit : kotlin.Int = 56 // kotlin.Int | Maximum results
            //val offset : kotlin.Int = 56 // kotlin.Int | Results offset
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseAuditEntriesResponse = apiInstance.queryAuditEntriesV1AuditEntriesGet(startTime, endTime, actor, eventType, entityId, search, severity, outcome, limit, offset, authorization)
            //result shouldBe ("TODO")
        }

        // to test searchAuditTrailsV1AuditSearchPost
        should("test searchAuditTrailsV1AuditSearchPost") {
            // uncomment below to test searchAuditTrailsV1AuditSearchPost
            //val searchText : kotlin.String = searchText_example // kotlin.String | Text to search for
            //val entityId : kotlin.String = entityId_example // kotlin.String | Filter by entity ID
            //val severity : kotlin.String = severity_example // kotlin.String | Filter by severity
            //val outcome : kotlin.String = outcome_example // kotlin.String | Filter by outcome
            //val limit : kotlin.Int = 56 // kotlin.Int | Maximum results
            //val offset : kotlin.Int = 56 // kotlin.Int | Results offset
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseAuditEntriesResponse = apiInstance.searchAuditTrailsV1AuditSearchPost(searchText, entityId, severity, outcome, limit, offset, authorization)
            //result shouldBe ("TODO")
        }

        // to test verifyAuditEntryV1AuditVerifyEntryIdPost
        should("test verifyAuditEntryV1AuditVerifyEntryIdPost") {
            // uncomment below to test verifyAuditEntryV1AuditVerifyEntryIdPost
            //val entryId : kotlin.String = entryId_example // kotlin.String | Audit entry ID to verify
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseVerificationReport = apiInstance.verifyAuditEntryV1AuditVerifyEntryIdPost(entryId, authorization)
            //result shouldBe ("TODO")
        }

    }
}
