/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.ConfigApi
import ai.ciris.api.models.ConfigUpdate
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.SuccessResponseConfigItemResponse
import ai.ciris.api.models.SuccessResponseConfigListResponse
import ai.ciris.api.models.SuccessResponseDictStrStr

class ConfigApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigApi
        //val apiInstance = ConfigApi()

        // to test deleteConfigV1ConfigKeyDelete
        should("test deleteConfigV1ConfigKeyDelete") {
            // uncomment below to test deleteConfigV1ConfigKeyDelete
            //val key : kotlin.String = key_example // kotlin.String | Configuration key
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseDictStrStr = apiInstance.deleteConfigV1ConfigKeyDelete(key, authorization)
            //result shouldBe ("TODO")
        }

        // to test getConfigV1ConfigKeyGet
        should("test getConfigV1ConfigKeyGet") {
            // uncomment below to test getConfigV1ConfigKeyGet
            //val key : kotlin.String = key_example // kotlin.String | Configuration key
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseConfigItemResponse = apiInstance.getConfigV1ConfigKeyGet(key, authorization)
            //result shouldBe ("TODO")
        }

        // to test listConfigsV1ConfigGet
        should("test listConfigsV1ConfigGet") {
            // uncomment below to test listConfigsV1ConfigGet
            //val prefix : kotlin.String = prefix_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseConfigListResponse = apiInstance.listConfigsV1ConfigGet(prefix, authorization)
            //result shouldBe ("TODO")
        }

        // to test updateConfigV1ConfigKeyPut
        should("test updateConfigV1ConfigKeyPut") {
            // uncomment below to test updateConfigV1ConfigKeyPut
            //val key : kotlin.String = key_example // kotlin.String | Configuration key
            //val configUpdate : ConfigUpdate =  // ConfigUpdate |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseConfigItemResponse = apiInstance.updateConfigV1ConfigKeyPut(key, configUpdate, authorization)
            //result shouldBe ("TODO")
        }

    }
}
