/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.ConnectorsApi
import ai.ciris.api.models.ConnectorRegistrationRequest
import ai.ciris.api.models.ConnectorUpdateRequest
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.StandardResponse

class ConnectorsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConnectorsApi
        //val apiInstance = ConnectorsApi()

        // to test deleteConnectorV1ConnectorsConnectorIdDelete
        should("test deleteConnectorV1ConnectorsConnectorIdDelete") {
            // uncomment below to test deleteConnectorV1ConnectorsConnectorIdDelete
            //val connectorId : kotlin.String = connectorId_example // kotlin.String |
            //val result : StandardResponse = apiInstance.deleteConnectorV1ConnectorsConnectorIdDelete(connectorId)
            //result shouldBe ("TODO")
        }

        // to test listConnectorsV1ConnectorsGet
        should("test listConnectorsV1ConnectorsGet") {
            // uncomment below to test listConnectorsV1ConnectorsGet
            //val connectorType : kotlin.String = connectorType_example // kotlin.String |
            //val result : StandardResponse = apiInstance.listConnectorsV1ConnectorsGet(connectorType)
            //result shouldBe ("TODO")
        }

        // to test registerSqlConnectorV1ConnectorsSqlPost
        should("test registerSqlConnectorV1ConnectorsSqlPost") {
            // uncomment below to test registerSqlConnectorV1ConnectorsSqlPost
            //val connectorRegistrationRequest : ConnectorRegistrationRequest =  // ConnectorRegistrationRequest |
            //val result : StandardResponse = apiInstance.registerSqlConnectorV1ConnectorsSqlPost(connectorRegistrationRequest)
            //result shouldBe ("TODO")
        }

        // to test testConnectorV1ConnectorsConnectorIdTestPost
        should("test testConnectorV1ConnectorsConnectorIdTestPost") {
            // uncomment below to test testConnectorV1ConnectorsConnectorIdTestPost
            //val connectorId : kotlin.String = connectorId_example // kotlin.String |
            //val result : StandardResponse = apiInstance.testConnectorV1ConnectorsConnectorIdTestPost(connectorId)
            //result shouldBe ("TODO")
        }

        // to test updateConnectorV1ConnectorsConnectorIdPatch
        should("test updateConnectorV1ConnectorsConnectorIdPatch") {
            // uncomment below to test updateConnectorV1ConnectorsConnectorIdPatch
            //val connectorId : kotlin.String = connectorId_example // kotlin.String |
            //val connectorUpdateRequest : ConnectorUpdateRequest =  // ConnectorUpdateRequest |
            //val result : StandardResponse = apiInstance.updateConnectorV1ConnectorsConnectorIdPatch(connectorId, connectorUpdateRequest)
            //result shouldBe ("TODO")
        }

    }
}
