/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.ConsentApi
import ai.ciris.api.models.ConsentAuditEntry
import ai.ciris.api.models.ConsentCategoriesResponse
import ai.ciris.api.models.ConsentCleanupResponse
import ai.ciris.api.models.ConsentDecayStatus
import ai.ciris.api.models.ConsentImpactReport
import ai.ciris.api.models.ConsentQueryResponse
import ai.ciris.api.models.ConsentRequest
import ai.ciris.api.models.ConsentStatus
import ai.ciris.api.models.ConsentStatusResponse
import ai.ciris.api.models.ConsentStreamsResponse
import ai.ciris.api.models.DSARInitiateResponse
import ai.ciris.api.models.DSARStatusResponse
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.PartnershipStatusResponse

class ConsentApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConsentApi
        //val apiInstance = ConsentApi()

        // to test checkPartnershipStatusV1ConsentPartnershipStatusGet
        should("test checkPartnershipStatusV1ConsentPartnershipStatusGet") {
            // uncomment below to test checkPartnershipStatusV1ConsentPartnershipStatusGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : PartnershipStatusResponse = apiInstance.checkPartnershipStatusV1ConsentPartnershipStatusGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test cleanupExpiredV1ConsentCleanupPost
        should("test cleanupExpiredV1ConsentCleanupPost") {
            // uncomment below to test cleanupExpiredV1ConsentCleanupPost
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentCleanupResponse = apiInstance.cleanupExpiredV1ConsentCleanupPost(authorization)
            //result shouldBe ("TODO")
        }

        // to test getAuditTrailV1ConsentAuditGet
        should("test getAuditTrailV1ConsentAuditGet") {
            // uncomment below to test getAuditTrailV1ConsentAuditGet
            //val limit : kotlin.Int = 56 // kotlin.Int |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.collections.List<ConsentAuditEntry> = apiInstance.getAuditTrailV1ConsentAuditGet(limit, authorization)
            //result shouldBe ("TODO")
        }

        // to test getConsentCategoriesV1ConsentCategoriesGet
        should("test getConsentCategoriesV1ConsentCategoriesGet") {
            // uncomment below to test getConsentCategoriesV1ConsentCategoriesGet
            //val result : ConsentCategoriesResponse = apiInstance.getConsentCategoriesV1ConsentCategoriesGet()
            //result shouldBe ("TODO")
        }

        // to test getConsentStatusV1ConsentStatusGet
        should("test getConsentStatusV1ConsentStatusGet") {
            // uncomment below to test getConsentStatusV1ConsentStatusGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentStatusResponse = apiInstance.getConsentStatusV1ConsentStatusGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getConsentStreamsV1ConsentStreamsGet
        should("test getConsentStreamsV1ConsentStreamsGet") {
            // uncomment below to test getConsentStreamsV1ConsentStreamsGet
            //val result : ConsentStreamsResponse = apiInstance.getConsentStreamsV1ConsentStreamsGet()
            //result shouldBe ("TODO")
        }

        // to test getDsarStatusV1ConsentDsarStatusRequestIdGet
        should("test getDsarStatusV1ConsentDsarStatusRequestIdGet") {
            // uncomment below to test getDsarStatusV1ConsentDsarStatusRequestIdGet
            //val requestId : kotlin.String = requestId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : DSARStatusResponse = apiInstance.getDsarStatusV1ConsentDsarStatusRequestIdGet(requestId, authorization)
            //result shouldBe ("TODO")
        }

        // to test getImpactReportV1ConsentImpactGet
        should("test getImpactReportV1ConsentImpactGet") {
            // uncomment below to test getImpactReportV1ConsentImpactGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentImpactReport = apiInstance.getImpactReportV1ConsentImpactGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test grantConsentV1ConsentGrantPost
        should("test grantConsentV1ConsentGrantPost") {
            // uncomment below to test grantConsentV1ConsentGrantPost
            //val consentRequest : ConsentRequest =  // ConsentRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentStatus = apiInstance.grantConsentV1ConsentGrantPost(consentRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test initiateDsarV1ConsentDsarInitiatePost
        should("test initiateDsarV1ConsentDsarInitiatePost") {
            // uncomment below to test initiateDsarV1ConsentDsarInitiatePost
            //val requestType : kotlin.String = requestType_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : DSARInitiateResponse = apiInstance.initiateDsarV1ConsentDsarInitiatePost(requestType, authorization)
            //result shouldBe ("TODO")
        }

        // to test queryConsentsV1ConsentQueryGet
        should("test queryConsentsV1ConsentQueryGet") {
            // uncomment below to test queryConsentsV1ConsentQueryGet
            //val status : kotlin.String = status_example // kotlin.String |
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentQueryResponse = apiInstance.queryConsentsV1ConsentQueryGet(status, userId, authorization)
            //result shouldBe ("TODO")
        }

        // to test revokeConsentV1ConsentRevokePost
        should("test revokeConsentV1ConsentRevokePost") {
            // uncomment below to test revokeConsentV1ConsentRevokePost
            //val reason : kotlin.String = reason_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : ConsentDecayStatus = apiInstance.revokeConsentV1ConsentRevokePost(reason, authorization)
            //result shouldBe ("TODO")
        }

    }
}
