/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.EmergencyApi
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.ResponseGetSystemStatusV1TransparencyStatusGetValue
import ai.ciris.api.models.SuccessResponseEmergencyShutdownStatus
import ai.ciris.api.models.WASignedCommand

class EmergencyApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EmergencyApi
        //val apiInstance = EmergencyApi()

        // to test emergencyShutdownEmergencyShutdownPost
        should("test emergencyShutdownEmergencyShutdownPost") {
            // uncomment below to test emergencyShutdownEmergencyShutdownPost
            //val waSignedCommand : WASignedCommand =  // WASignedCommand |
            //val result : SuccessResponseEmergencyShutdownStatus = apiInstance.emergencyShutdownEmergencyShutdownPost(waSignedCommand)
            //result shouldBe ("TODO")
        }

        // to test testEmergencyEndpointEmergencyTestGet
        should("test testEmergencyEndpointEmergencyTestGet") {
            // uncomment below to test testEmergencyEndpointEmergencyTestGet
            //val result : kotlin.collections.Map<kotlin.String, ResponseGetSystemStatusV1TransparencyStatusGetValue> = apiInstance.testEmergencyEndpointEmergencyTestGet()
            //result shouldBe ("TODO")
        }

    }
}
