/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.SystemExtensionsApi
import ai.ciris.api.models.BodyValue
import ai.ciris.api.models.CircuitBreakerResetRequest
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.ServicePriorityUpdateRequest
import ai.ciris.api.models.SuccessResponseCircuitBreakerResetResponse
import ai.ciris.api.models.SuccessResponseListProcessorStateInfo
import ai.ciris.api.models.SuccessResponseProcessorQueueStatus
import ai.ciris.api.models.SuccessResponseServiceHealthStatus
import ai.ciris.api.models.SuccessResponseServicePriorityUpdateResponse
import ai.ciris.api.models.SuccessResponseServiceSelectionExplanation
import ai.ciris.api.models.SuccessResponseSingleStepResponse

class SystemExtensionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemExtensionsApi
        //val apiInstance = SystemExtensionsApi()

        // to test getProcessingQueueStatusV1SystemRuntimeQueueGet
        should("test getProcessingQueueStatusV1SystemRuntimeQueueGet") {
            // uncomment below to test getProcessingQueueStatusV1SystemRuntimeQueueGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseProcessorQueueStatus = apiInstance.getProcessingQueueStatusV1SystemRuntimeQueueGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getProcessorStatesV1SystemProcessorsGet
        should("test getProcessorStatesV1SystemProcessorsGet") {
            // uncomment below to test getProcessorStatesV1SystemProcessorsGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseListProcessorStateInfo = apiInstance.getProcessorStatesV1SystemProcessorsGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getServiceHealthDetailsV1SystemServicesHealthGet
        should("test getServiceHealthDetailsV1SystemServicesHealthGet") {
            // uncomment below to test getServiceHealthDetailsV1SystemServicesHealthGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseServiceHealthStatus = apiInstance.getServiceHealthDetailsV1SystemServicesHealthGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getServiceSelectionExplanationV1SystemServicesSelectionLogicGet
        should("test getServiceSelectionExplanationV1SystemServicesSelectionLogicGet") {
            // uncomment below to test getServiceSelectionExplanationV1SystemServicesSelectionLogicGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseServiceSelectionExplanation = apiInstance.getServiceSelectionExplanationV1SystemServicesSelectionLogicGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test reasoningStreamV1SystemRuntimeReasoningStreamGet
        should("test reasoningStreamV1SystemRuntimeReasoningStreamGet") {
            // uncomment below to test reasoningStreamV1SystemRuntimeReasoningStreamGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.Any = apiInstance.reasoningStreamV1SystemRuntimeReasoningStreamGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test resetServiceCircuitBreakersV1SystemServicesCircuitBreakersResetPost
        should("test resetServiceCircuitBreakersV1SystemServicesCircuitBreakersResetPost") {
            // uncomment below to test resetServiceCircuitBreakersV1SystemServicesCircuitBreakersResetPost
            //val circuitBreakerResetRequest : CircuitBreakerResetRequest =  // CircuitBreakerResetRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseCircuitBreakerResetResponse = apiInstance.resetServiceCircuitBreakersV1SystemServicesCircuitBreakersResetPost(circuitBreakerResetRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test singleStepProcessorV1SystemRuntimeStepPost
        should("test singleStepProcessorV1SystemRuntimeStepPost") {
            // uncomment below to test singleStepProcessorV1SystemRuntimeStepPost
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val requestBody : kotlin.collections.Map<kotlin.String, BodyValue> = Object // kotlin.collections.Map<kotlin.String, BodyValue> |
            //val result : SuccessResponseSingleStepResponse = apiInstance.singleStepProcessorV1SystemRuntimeStepPost(authorization, requestBody)
            //result shouldBe ("TODO")
        }

        // to test updateServicePriorityV1SystemServicesProviderNamePriorityPut
        should("test updateServicePriorityV1SystemServicesProviderNamePriorityPut") {
            // uncomment below to test updateServicePriorityV1SystemServicesProviderNamePriorityPut
            //val providerName : kotlin.String = providerName_example // kotlin.String |
            //val servicePriorityUpdateRequest : ServicePriorityUpdateRequest =  // ServicePriorityUpdateRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseServicePriorityUpdateResponse = apiInstance.updateServicePriorityV1SystemServicesProviderNamePriorityPut(providerName, servicePriorityUpdateRequest, authorization)
            //result shouldBe ("TODO")
        }

    }
}
