/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.TelemetryApi
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.SuccessResponse
import ai.ciris.api.models.SuccessResponseDetailedMetric
import ai.ciris.api.models.SuccessResponseLogsResponse
import ai.ciris.api.models.SuccessResponseMetricsResponse
import ai.ciris.api.models.SuccessResponseQueryResponse
import ai.ciris.api.models.SuccessResponseResourceTelemetryResponse
import ai.ciris.api.models.SuccessResponseSystemOverview
import ai.ciris.api.models.SuccessResponseTracesResponse
import ai.ciris.api.models.TelemetryQuery

class TelemetryApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetryApi
        //val apiInstance = TelemetryApi()

        // to test getDetailedMetricV1TelemetryMetricsMetricNameGet
        should("test getDetailedMetricV1TelemetryMetricsMetricNameGet") {
            // uncomment below to test getDetailedMetricV1TelemetryMetricsMetricNameGet
            //val metricName : kotlin.String = metricName_example // kotlin.String |
            //val hours : kotlin.Int = 56 // kotlin.Int | Hours of history to include
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseDetailedMetric = apiInstance.getDetailedMetricV1TelemetryMetricsMetricNameGet(metricName, hours, authorization)
            //result shouldBe ("TODO")
        }

        // to test getDetailedMetricsV1TelemetryMetricsGet
        should("test getDetailedMetricsV1TelemetryMetricsGet") {
            // uncomment below to test getDetailedMetricsV1TelemetryMetricsGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseMetricsResponse = apiInstance.getDetailedMetricsV1TelemetryMetricsGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getOtlpTelemetryV1TelemetryOtlpSignalGet
        should("test getOtlpTelemetryV1TelemetryOtlpSignalGet") {
            // uncomment below to test getOtlpTelemetryV1TelemetryOtlpSignalGet
            //val signal : kotlin.String = signal_example // kotlin.String |
            //val limit : kotlin.Int = 56 // kotlin.Int | Maximum items to return
            //val startTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Start of time range
            //val endTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | End of time range
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.Any = apiInstance.getOtlpTelemetryV1TelemetryOtlpSignalGet(signal, limit, startTime, endTime, authorization)
            //result shouldBe ("TODO")
        }

        // to test getReasoningTracesV1TelemetryTracesGet
        should("test getReasoningTracesV1TelemetryTracesGet") {
            // uncomment below to test getReasoningTracesV1TelemetryTracesGet
            //val limit : kotlin.Int = 56 // kotlin.Int | Maximum traces to return
            //val startTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Start of time range
            //val endTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | End of time range
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseTracesResponse = apiInstance.getReasoningTracesV1TelemetryTracesGet(limit, startTime, endTime, authorization)
            //result shouldBe ("TODO")
        }

        // to test getResourceHistoryV1TelemetryResourcesHistoryGet
        should("test getResourceHistoryV1TelemetryResourcesHistoryGet") {
            // uncomment below to test getResourceHistoryV1TelemetryResourcesHistoryGet
            //val hours : kotlin.Int = 56 // kotlin.Int | Hours of history
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponse = apiInstance.getResourceHistoryV1TelemetryResourcesHistoryGet(hours, authorization)
            //result shouldBe ("TODO")
        }

        // to test getResourceTelemetryV1TelemetryResourcesGet
        should("test getResourceTelemetryV1TelemetryResourcesGet") {
            // uncomment below to test getResourceTelemetryV1TelemetryResourcesGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseResourceTelemetryResponse = apiInstance.getResourceTelemetryV1TelemetryResourcesGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getSystemLogsV1TelemetryLogsGet
        should("test getSystemLogsV1TelemetryLogsGet") {
            // uncomment below to test getSystemLogsV1TelemetryLogsGet
            //val startTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | Start of time range
            //val endTime : kotlin.time.Instant = 2013-10-20T19:20:30+01:00 // kotlin.time.Instant | End of time range
            //val level : kotlin.String = level_example // kotlin.String | Log level filter
            //val service : kotlin.String = service_example // kotlin.String | Service filter
            //val limit : kotlin.Int = 56 // kotlin.Int | Maximum logs to return
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseLogsResponse = apiInstance.getSystemLogsV1TelemetryLogsGet(startTime, endTime, level, service, limit, authorization)
            //result shouldBe ("TODO")
        }

        // to test getTelemetryOverviewV1TelemetryOverviewGet
        should("test getTelemetryOverviewV1TelemetryOverviewGet") {
            // uncomment below to test getTelemetryOverviewV1TelemetryOverviewGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseSystemOverview = apiInstance.getTelemetryOverviewV1TelemetryOverviewGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getUnifiedTelemetryV1TelemetryUnifiedGet
        should("test getUnifiedTelemetryV1TelemetryUnifiedGet") {
            // uncomment below to test getUnifiedTelemetryV1TelemetryUnifiedGet
            //val view : kotlin.String = view_example // kotlin.String | View type: summary|health|operational|detailed|performance|reliability
            //val category : kotlin.String = category_example // kotlin.String | Filter by category: buses|graph|infrastructure|governance|runtime|adapters|components|all
            //val format : kotlin.String = format_example // kotlin.String | Output format: json|prometheus|graphite
            //val live : kotlin.Boolean = true // kotlin.Boolean | Force live collection (bypass cache)
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.Any = apiInstance.getUnifiedTelemetryV1TelemetryUnifiedGet(view, category, format, live, authorization)
            //result shouldBe ("TODO")
        }

        // to test queryTelemetryV1TelemetryQueryPost
        should("test queryTelemetryV1TelemetryQueryPost") {
            // uncomment below to test queryTelemetryV1TelemetryQueryPost
            //val telemetryQuery : TelemetryQuery =  // TelemetryQuery |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : SuccessResponseQueryResponse = apiInstance.queryTelemetryV1TelemetryQueryPost(telemetryQuery, authorization)
            //result shouldBe ("TODO")
        }

    }
}
