/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.TicketsApi
import ai.ciris.api.models.CreateTicketRequest
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.SOPMetadataResponse
import ai.ciris.api.models.StandardResponse
import ai.ciris.api.models.TicketResponse
import ai.ciris.api.models.UpdateTicketRequest

class TicketsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TicketsApi
        //val apiInstance = TicketsApi()

        // to test cancelTicketV1TicketsTicketIdDelete
        should("test cancelTicketV1TicketsTicketIdDelete") {
            // uncomment below to test cancelTicketV1TicketsTicketIdDelete
            //val ticketId : kotlin.String = ticketId_example // kotlin.String |
            //val result : StandardResponse = apiInstance.cancelTicketV1TicketsTicketIdDelete(ticketId)
            //result shouldBe ("TODO")
        }

        // to test createNewTicketV1TicketsPost
        should("test createNewTicketV1TicketsPost") {
            // uncomment below to test createNewTicketV1TicketsPost
            //val createTicketRequest : CreateTicketRequest =  // CreateTicketRequest |
            //val result : TicketResponse = apiInstance.createNewTicketV1TicketsPost(createTicketRequest)
            //result shouldBe ("TODO")
        }

        // to test getSopMetadataV1TicketsSopsSopGet
        should("test getSopMetadataV1TicketsSopsSopGet") {
            // uncomment below to test getSopMetadataV1TicketsSopsSopGet
            //val sop : kotlin.String = sop_example // kotlin.String |
            //val result : SOPMetadataResponse = apiInstance.getSopMetadataV1TicketsSopsSopGet(sop)
            //result shouldBe ("TODO")
        }

        // to test getTicketByIdV1TicketsTicketIdGet
        should("test getTicketByIdV1TicketsTicketIdGet") {
            // uncomment below to test getTicketByIdV1TicketsTicketIdGet
            //val ticketId : kotlin.String = ticketId_example // kotlin.String |
            //val result : TicketResponse = apiInstance.getTicketByIdV1TicketsTicketIdGet(ticketId)
            //result shouldBe ("TODO")
        }

        // to test listAllTicketsV1TicketsGet
        should("test listAllTicketsV1TicketsGet") {
            // uncomment below to test listAllTicketsV1TicketsGet
            //val sop : kotlin.String = sop_example // kotlin.String |
            //val ticketType : kotlin.String = ticketType_example // kotlin.String |
            //val statusFilter : kotlin.String = statusFilter_example // kotlin.String |
            //val email : kotlin.String = email_example // kotlin.String |
            //val limit : kotlin.Int = 56 // kotlin.Int |
            //val result : kotlin.collections.List<TicketResponse> = apiInstance.listAllTicketsV1TicketsGet(sop, ticketType, statusFilter, email, limit)
            //result shouldBe ("TODO")
        }

        // to test listSupportedSopsV1TicketsSopsGet
        should("test listSupportedSopsV1TicketsSopsGet") {
            // uncomment below to test listSupportedSopsV1TicketsSopsGet
            //val result : kotlin.collections.List<kotlin.String?> = apiInstance.listSupportedSopsV1TicketsSopsGet()
            //result shouldBe ("TODO")
        }

        // to test updateExistingTicketV1TicketsTicketIdPatch
        should("test updateExistingTicketV1TicketsTicketIdPatch") {
            // uncomment below to test updateExistingTicketV1TicketsTicketIdPatch
            //val ticketId : kotlin.String = ticketId_example // kotlin.String |
            //val updateTicketRequest : UpdateTicketRequest =  // UpdateTicketRequest |
            //val result : TicketResponse = apiInstance.updateExistingTicketV1TicketsTicketIdPatch(ticketId, updateTicketRequest)
            //result shouldBe ("TODO")
        }

    }
}
