/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.ciris.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.ciris.api.apis.UsersApi
import ai.ciris.api.models.APIKeyInfo
import ai.ciris.api.models.APIRole
import ai.ciris.api.models.ChangePasswordRequest
import ai.ciris.api.models.CreateUserRequest
import ai.ciris.api.models.DeactivateUserResponse
import ai.ciris.api.models.HTTPValidationError
import ai.ciris.api.models.LinkOAuthAccountRequest
import ai.ciris.api.models.MintWARequest
import ai.ciris.api.models.PaginatedResponseUserSummary
import ai.ciris.api.models.PermissionRequestResponse
import ai.ciris.api.models.PermissionRequestUser
import ai.ciris.api.models.UpdatePermissionsRequest
import ai.ciris.api.models.UpdateUserRequest
import ai.ciris.api.models.UpdateUserSettingsRequest
import ai.ciris.api.models.UserDetail
import ai.ciris.api.models.UserSettingsResponse
import ai.ciris.api.models.WAKeyCheckResponse
import ai.ciris.api.models.WARole

class UsersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UsersApi
        //val apiInstance = UsersApi()

        // to test changePasswordV1UsersUserIdPasswordPut
        should("test changePasswordV1UsersUserIdPasswordPut") {
            // uncomment below to test changePasswordV1UsersUserIdPasswordPut
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val changePasswordRequest : ChangePasswordRequest =  // ChangePasswordRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.collections.Map<kotlin.String, kotlin.String> = apiInstance.changePasswordV1UsersUserIdPasswordPut(userId, changePasswordRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test checkWaKeyExistsV1UsersWaKeyCheckGet
        should("test checkWaKeyExistsV1UsersWaKeyCheckGet") {
            // uncomment below to test checkWaKeyExistsV1UsersWaKeyCheckGet
            //val path : kotlin.String = path_example // kotlin.String | Filename of private key to check
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : WAKeyCheckResponse = apiInstance.checkWaKeyExistsV1UsersWaKeyCheckGet(path, authorization)
            //result shouldBe ("TODO")
        }

        // to test createUserV1UsersPost
        should("test createUserV1UsersPost") {
            // uncomment below to test createUserV1UsersPost
            //val createUserRequest : CreateUserRequest =  // CreateUserRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.createUserV1UsersPost(createUserRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test deactivateUserV1UsersUserIdDelete
        should("test deactivateUserV1UsersUserIdDelete") {
            // uncomment below to test deactivateUserV1UsersUserIdDelete
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : DeactivateUserResponse = apiInstance.deactivateUserV1UsersUserIdDelete(userId, authorization)
            //result shouldBe ("TODO")
        }

        // to test getMySettingsV1UsersMeSettingsGet
        should("test getMySettingsV1UsersMeSettingsGet") {
            // uncomment below to test getMySettingsV1UsersMeSettingsGet
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserSettingsResponse = apiInstance.getMySettingsV1UsersMeSettingsGet(authorization)
            //result shouldBe ("TODO")
        }

        // to test getPermissionRequestsV1UsersPermissionRequestsGet
        should("test getPermissionRequestsV1UsersPermissionRequestsGet") {
            // uncomment below to test getPermissionRequestsV1UsersPermissionRequestsGet
            //val includeGranted : kotlin.Boolean = true // kotlin.Boolean | Include users who already have permissions
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.collections.List<PermissionRequestUser> = apiInstance.getPermissionRequestsV1UsersPermissionRequestsGet(includeGranted, authorization)
            //result shouldBe ("TODO")
        }

        // to test getUserV1UsersUserIdGet
        should("test getUserV1UsersUserIdGet") {
            // uncomment below to test getUserV1UsersUserIdGet
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.getUserV1UsersUserIdGet(userId, authorization)
            //result shouldBe ("TODO")
        }

        // to test linkOauthAccountV1UsersUserIdOauthLinksPost
        should("test linkOauthAccountV1UsersUserIdOauthLinksPost") {
            // uncomment below to test linkOauthAccountV1UsersUserIdOauthLinksPost
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val linkOAuthAccountRequest : LinkOAuthAccountRequest =  // LinkOAuthAccountRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.linkOauthAccountV1UsersUserIdOauthLinksPost(userId, linkOAuthAccountRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test listUserApiKeysV1UsersUserIdApiKeysGet
        should("test listUserApiKeysV1UsersUserIdApiKeysGet") {
            // uncomment below to test listUserApiKeysV1UsersUserIdApiKeysGet
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : kotlin.collections.List<APIKeyInfo> = apiInstance.listUserApiKeysV1UsersUserIdApiKeysGet(userId, authorization)
            //result shouldBe ("TODO")
        }

        // to test listUsersV1UsersGet
        should("test listUsersV1UsersGet") {
            // uncomment below to test listUsersV1UsersGet
            //val page : kotlin.Int = 56 // kotlin.Int |
            //val pageSize : kotlin.Int = 56 // kotlin.Int |
            //val search : kotlin.String = search_example // kotlin.String |
            //val authType : kotlin.String = authType_example // kotlin.String |
            //val apiRole : APIRole =  // APIRole |
            //val waRole : WARole =  // WARole |
            //val isActive : kotlin.Boolean = true // kotlin.Boolean |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : PaginatedResponseUserSummary = apiInstance.listUsersV1UsersGet(page, pageSize, search, authType, apiRole, waRole, isActive, authorization)
            //result shouldBe ("TODO")
        }

        // to test mintWiseAuthorityV1UsersUserIdMintWaPost
        should("test mintWiseAuthorityV1UsersUserIdMintWaPost") {
            // uncomment below to test mintWiseAuthorityV1UsersUserIdMintWaPost
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val mintWARequest : MintWARequest =  // MintWARequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.mintWiseAuthorityV1UsersUserIdMintWaPost(userId, mintWARequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test requestPermissionsV1UsersRequestPermissionsPost
        should("test requestPermissionsV1UsersRequestPermissionsPost") {
            // uncomment below to test requestPermissionsV1UsersRequestPermissionsPost
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : PermissionRequestResponse = apiInstance.requestPermissionsV1UsersRequestPermissionsPost(authorization)
            //result shouldBe ("TODO")
        }

        // to test unlinkOauthAccountV1UsersUserIdOauthLinksProviderExternalIdDelete
        should("test unlinkOauthAccountV1UsersUserIdOauthLinksProviderExternalIdDelete") {
            // uncomment below to test unlinkOauthAccountV1UsersUserIdOauthLinksProviderExternalIdDelete
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val provider : kotlin.String = provider_example // kotlin.String |
            //val externalId : kotlin.String = externalId_example // kotlin.String |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.unlinkOauthAccountV1UsersUserIdOauthLinksProviderExternalIdDelete(userId, provider, externalId, authorization)
            //result shouldBe ("TODO")
        }

        // to test updateMySettingsV1UsersMeSettingsPut
        should("test updateMySettingsV1UsersMeSettingsPut") {
            // uncomment below to test updateMySettingsV1UsersMeSettingsPut
            //val updateUserSettingsRequest : UpdateUserSettingsRequest =  // UpdateUserSettingsRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserSettingsResponse = apiInstance.updateMySettingsV1UsersMeSettingsPut(updateUserSettingsRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test updateUserPermissionsV1UsersUserIdPermissionsPut
        should("test updateUserPermissionsV1UsersUserIdPermissionsPut") {
            // uncomment below to test updateUserPermissionsV1UsersUserIdPermissionsPut
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val updatePermissionsRequest : UpdatePermissionsRequest =  // UpdatePermissionsRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.updateUserPermissionsV1UsersUserIdPermissionsPut(userId, updatePermissionsRequest, authorization)
            //result shouldBe ("TODO")
        }

        // to test updateUserV1UsersUserIdPut
        should("test updateUserV1UsersUserIdPut") {
            // uncomment below to test updateUserV1UsersUserIdPut
            //val userId : kotlin.String = userId_example // kotlin.String |
            //val updateUserRequest : UpdateUserRequest =  // UpdateUserRequest |
            //val authorization : kotlin.String = authorization_example // kotlin.String |
            //val result : UserDetail = apiInstance.updateUserV1UsersUserIdPut(userId, updateUserRequest, authorization)
            //result shouldBe ("TODO")
        }

    }
}
